/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */



@protocol _NCWidgetController_Host_IPC
-(void)__setHasContent:(BOOL)content forWidgetWithBundleIdentifier:(id)bundleIdentifier;
@end

