/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */



@protocol _NCWidgetViewController_Host_IPC
-(void)__closeTransactionForAppearanceCallWithState:(int)state withIdentifier:(id)identifier;
-(void)__requestLaunchOfURL:(id)url;
-(void)__requestPreferredViewHeight:(float)height usingAutolayout:(BOOL)autolayout requestIdentifier:(id)identifier;
@end

