/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class UILabel;

__attribute__((visibility("hidden")))
@interface _SBBrokenWidgetView : XXUnknownSuperclass {
	UILabel* _label;
}
+(void)_configureLabelForCurrentGraphicsQuality:(id)currentGraphicsQuality;
-(void)_backgroundContrastDidChange:(id)_backgroundContrast;
-(void)layoutSubviews;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
@end

