/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBIconZoomAnimator.h"
#import "SBIconListLayoutDelegate.h"

@class SBFolderZoomSettings, SBFolderIconView, SBFloatyFolderView, NSString;

__attribute__((visibility("hidden")))
@interface _SBInnerFolderIconZoomAnimator : SBIconZoomAnimator <SBIconListLayoutDelegate> {
	SBFloatyFolderView* _folderView;
	SBFolderIconView* _folderIconView;
	CGAffineTransform _folderIconViewScaleTransform;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(retain, nonatomic) SBFolderZoomSettings* settings;
-(void)_calculateZoomedOffset:(CGPoint*)offset scale:(CGPoint*)scale forIcon:(id)icon withView:(id)view;
-(void)_applyFolderFadeForZoomFraction:(float)zoomFraction;
-(void)_applyIconTransformForZoomFraction:(float)zoomFraction;
-(void)_applyIconCrossfadeForZoomFraction:(float)zoomFraction;
-(void)_animateToFraction:(float)fraction afterDelay:(double)delay withSharedCompletion:(id)sharedCompletion;
-(unsigned)_numberOfSignificantAnimations;
-(void)_cleanupAnimation;
-(void)_setAnimationFraction:(float)fraction;
-(void)_prepareAnimation;
-(void)dealloc;
-(id)initWithFolderController:(id)folderController iconView:(id)view iconZoomScaleDimension:(CGPoint)dimension;
@end

