/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBUIRemoteAlertHostInterface.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSString;
@protocol _SBRemoteAlertHostViewControllerDelegate;

__attribute__((visibility("hidden")))
@interface _SBRemoteAlertHostViewController : XXUnknownSuperclass <SBUIRemoteAlertHostInterface> {
	id<_SBRemoteAlertHostViewControllerDelegate> _delegate;
	NSString* _serviceClassName;
}
@property(copy, nonatomic) NSString* serviceClassName;
@property(assign, nonatomic) id<_SBRemoteAlertHostViewControllerDelegate> delegate;
+(id)serviceViewControllerInterface;
+(id)exportedInterface;
-(void)viewServiceDidTerminateWithError:(id)viewService;
-(void)setSupportedInterfaceOrientationOverride:(unsigned)override;
-(void)setShouldDisableFadeInAnimation:(BOOL)disableFadeInAnimation;
-(void)setShouldDismissOnUILock:(BOOL)dismissOnUILock;
-(void)setStatusBarHidden:(BOOL)hidden withDuration:(double)duration;
-(void)setDesiredAutoLockDuration:(double)duration;
-(void)setIdleTimerDisabled:(BOOL)disabled forReason:(id)reason;
-(void)setDesiredStatusBarStyleOverrides:(int)overrides;
-(void)setDismissalAnimationStyle:(int)style;
-(void)setAllowsAlertStacking:(BOOL)stacking;
-(void)setAllowsMenuButtonDismissal:(BOOL)dismissal;
-(void)setBackgroundStyle:(int)style withDuration:(double)duration;
-(void)setWallpaperTunnelActive:(BOOL)active;
-(void)setDesiredHardwareButtonEvents:(int)events;
-(void)dismissAndLockUIIfNecessary;
-(void)dismiss;
-(void)setAllowsBanners:(BOOL)banners;
-(void)dealloc;
-(id)description;
@end

