/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol _SBRemoteAlertHostViewControllerDelegate <NSObject>
-(void)remoteAlertWantsToLockUIAndDismiss;
-(void)remoteAlertWantstoSetSupportedInterfaceOrientationOverride:(unsigned)override;
-(void)remoteAlertWantsToDisableFadeInAnimation:(BOOL)animation;
-(void)remoteAlertWantsToDismissOnUILock:(BOOL)dismissOnUILock;
-(void)remoteAlertWantsToSetStatusBarHidden:(BOOL)setStatusBarHidden withDuration:(double)duration;
-(void)remoteAlertWantsToSetAutoLockDuration:(double)setAutoLockDuration;
-(void)remoteAlertWantsToSetIdleTimerDisabled:(BOOL)setIdleTimerDisabled forReason:(id)reason;
-(void)remoteAlertWantsToSetDesiredStatusBarStyleOverrides:(int)setDesiredStatusBarStyleOverrides;
-(void)remoteAlertWantstoSetDismissalAnimationStyle:(int)style;
-(void)remoteAlertWantsToAllowAlertStacking:(BOOL)allowAlertStacking;
-(void)remoteAlertWantsMenuButtonDismissal:(BOOL)dismissal;
-(void)remoteAlertWantsToSetBackgroundStyle:(int)setBackgroundStyle withDuration:(double)duration;
-(void)remoteAlertWantsWallpaperTunnelActive:(BOOL)active;
-(void)remoteAlertDidTerminateWithError:(id)remoteAlert;
-(void)remoteAlertWantsToUpdateAllowedHardwareButtonEvents:(int)updateAllowedHardwareButtonEvents;
-(void)remoteAlertWantsToAllowBanners:(BOOL)allowBanners;
@end

