/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "_SBUIWidgetHost.h"
#import "SBWidgetViewController.h"

@class NSString, _SBUIWidgetViewController;

__attribute__((visibility("hidden")))
@interface _SBWidgetViewControllerInProcess : SBWidgetViewController <_SBUIWidgetHost> {
	_SBUIWidgetViewController* _widgetViewController;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(retain, nonatomic) _SBUIWidgetViewController* widgetViewController;
-(void)hostDidDismiss;
-(void)hostWillDismiss;
-(void)hostDidPresent;
-(void)hostWillPresent;
-(void)invalidatePreferredViewSize;
-(void)requestLaunchOfURL:(id)url;
-(void)requestPresentationOfViewController:(id)viewController presentationStyle:(int)style context:(id)context completion:(id)completion;
-(void)viewDidLoad;
-(void)updateContentWidth:(float)width;
-(void)requestPreferredViewHeightWithHandler:(id)handler;
-(void)dealloc;
-(id)initWithWidgetIdentifier:(id)widgetIdentifier bundlePath:(id)path;
-(id)_newWidgetViewControllerWithIdentifier:(id)identifier bundlePath:(id)path;
@end

