/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "_NCWidgetViewController_Host_IPC.h"
#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSObject, _SBWidgetViewControllerOutOfProcess;
@protocol OS_dispatch_queue;

__attribute__((visibility("hidden")))
@interface _SBWidgetRemoteViewController : XXUnknownSuperclass <_NCWidgetViewController_Host_IPC> {
	BOOL _valid;
	_SBWidgetViewControllerOutOfProcess* _managingHost;
	NSObject<OS_dispatch_queue>* _managingHostQueue;
}
@property(readonly, assign, nonatomic) NSObject<OS_dispatch_queue>* managingHostQueue;
@property(assign, nonatomic) _SBWidgetViewControllerOutOfProcess* managingHost;
@property(assign, nonatomic, getter=_isValid, setter=_setValid:) BOOL valid;
+(id)exportedInterface;
+(id)serviceViewControllerInterface;
-(void)viewServiceDidTerminateWithError:(id)viewService;
-(void)__closeTransactionForAppearanceCallWithState:(int)state withIdentifier:(id)identifier;
-(void)__requestLaunchOfURL:(id)url;
-(void)__requestPreferredViewHeight:(float)height usingAutolayout:(BOOL)autolayout requestIdentifier:(id)identifier;
-(void)_performUpdateWithReplyHandler:(id)replyHandler;
-(void)_requestEncodedLayerTreeWithReplyHandler:(id)replyHandler;
-(void)_openTransactionForAppearanceCallWithState:(int)state withIdentifier:(id)identifier;
-(void)_viewWillTransitionToSize:(CGSize)_view requestIdentifier:(id)identifier;
-(void)_performOutstandingCompletionWithRequestIdentifier:(id)requestIdentifier;
-(void)_performOutstandingAnimationsWithRequestIdentifier:(id)requestIdentifier;
-(void)_setWidgetIdentifier:(id)identifier;
-(void)__viewServiceDidUnregisterScrollToTopView;
-(void)__viewServiceDidRegisterScrollToTopView;
-(BOOL)_serviceHasScrollToTopView;
-(BOOL)__shouldRemoteViewControllerFenceOperations;
-(id)disconnect;
-(void)dealloc;
-(id)initWithNibName:(id)nibName bundle:(id)bundle;
@end

