/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol _UIActionSliderDelegate <NSObject>
@optional
-(void)actionSliderDidCancelSlide:(id)actionSlider;
-(void)actionSliderDidCompleteSlide:(id)actionSlider;
-(void)actionSlider:(id)slider didUpdateSlideWithValue:(float)value;
-(void)actionSliderDidBeginSlide:(id)actionSlider;
@end

