/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol BSSettingDescriptionProvider <NSObject>
-(id)valueDescriptionForFlag:(int)flag object:(id)object ofSetting:(unsigned)setting;
-(id)keyDescriptionForSetting:(unsigned)setting;
@end

