/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol BSWatchdogDelegate <NSObject>
@optional
-(void)watchdogCancelled:(id)cancelled;
-(void)watchdogFired:(id)fired;
-(void)watchdogStarted:(id)started;
@end

