/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol FBApplicationLibraryObserver <NSObject>
@optional
-(void)applicationLibrary:(id)library networkUsageDidChange:(BOOL)networkUsage;
-(void)applicationLibrary:(id)library didRemoveApplications:(id)applications;
-(void)applicationLibrary:(id)library didReplaceApplications:(id)applications withApplications:(id)applications3;
-(void)applicationLibrary:(id)library didAddApplications:(id)applications;
-(void)applicationLibrary:(id)library didCancelPlaceholders:(id)placeholders;
-(void)applicationLibrary:(id)library didAddPlaceholders:(id)placeholders;
@end

