/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol FBProcessObserver <NSObject>
@optional
-(void)process:(id)process stateDidChangeFromState:(id)state toState:(id)state3;
-(void)processDidExit:(id)process;
@end

