/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol FBUIApplicationServiceDelegate <NSObject>
@optional
-(void)applicationService:(id)service setNextWakeDate:(id)date forBundleIdentifier:(id)bundleIdentifier;
-(void)applicationService:(id)service getBadgeValueForBundleIdentifier:(id)bundleIdentifier withCompletion:(id)completion;
-(void)applicationService:(id)service setBadgeValue:(id)value forBundleIdentifier:(id)bundleIdentifier;
@end

