/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol FBWorkspaceDelegate <NSObject>
-(void)workspace:(id)workspace didReceiveDestroySceneRequestForIdentifier:(id)identifier withCompletion:(id)completion;
-(void)workspace:(id)workspace didReceiveCreateSceneRequestWithInitialClientSettings:(id)initialClientSettings withCompletion:(id)completion;
@end

