/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol LSBestAppSuggestionManagerDelegate <NSObject>
@optional
-(void)connectionInterrupted;
-(void)bestAppSuggestionChanged:(id)changed;
-(void)bestAppSuggestionMayHaveChanged;
@end

