/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "SBDisplayProtocol.h"
#import "SpringBoard-Structs.h"

@class SBDeactivationSettings, SBActivationSettings, NSHashTable, NSString, NSMutableDictionary, SBAlertView, SBStateSettings, SBAlertManager, UIScreen, UIViewController;
@protocol SBAlertDelegate;

__attribute__((visibility("hidden")))
@interface SBAlert : XXUnknownSuperclass <SBDisplayProtocol> {
	id<SBAlertDelegate> _alertDelegate;
	SBAlertView* _display;
	NSMutableDictionary* _dictionary;
	BOOL _isWallpaperTunnelActive;
	BOOL _backgroundStyleIsSet;
	int _backgroundStyle;
	BOOL _isForcingBackgroundStyleUpdate;
	BOOL _suppressesBanners;
	SBActivationSettings* _activationSettings;
	SBDeactivationSettings* _deactivationSettings;
	SBStateSettings* _stateSettings;
	int _orientationChangedEventsEnabled;
	BOOL _requestedDismissal;
	UIScreen* _targetScreen;
	NSHashTable* _observers;
	SBAlertManager* _alertManager;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(readonly, assign, nonatomic) BOOL wantsSupportedInterfaceOrientationsIgnoredDuringDeactivation;
@property(readonly, assign, nonatomic) UIViewController* viewControllerForSupportedInterfaceOrientations;
@property(readonly, assign, nonatomic) BOOL suppressesSiri;
@property(readonly, assign, nonatomic) BOOL suppressesControlCenter;
@property(readonly, assign, nonatomic) BOOL suppressesNotificationCenter;
@property(retain, nonatomic) SBAlertManager* alertManager;
@property(assign, nonatomic, getter=_requestedDismissal, setter=_setRequestedDismissal:) BOOL requestedDismissal;
@property(assign, nonatomic) BOOL suppressesBanners;
+(void)test;
+(void)registerForAlerts;
-(void)removeObserver:(id)observer;
-(void)addObserver:(id)observer;
-(BOOL)_isLockAlert;
-(void)_removeFromImpersonatedAppIfNecessary;
-(id)_impersonatesApplicationWithBundleID;
-(void)removeFromView;
-(void)alertViewIsReadyToDismiss:(id)dismiss;
-(void)setDisplay:(id)display;
-(void)setAlertDelegate:(id)delegate;
-(id)alertDelegate;
-(BOOL)_shouldDismissSwitcherOnActivation;
-(void)handleAutoLock;
-(BOOL)handleHeadsetButtonPressed:(BOOL)pressed;
-(BOOL)handleVolumeDownButtonPressed;
-(BOOL)handleVolumeUpButtonPressed;
-(BOOL)handleLockButtonPressed;
-(BOOL)hasTranslucentBackground;
-(BOOL)shouldPendAlertItemsWhileActive;
-(void)handleSlideshowHardwareButton;
-(BOOL)handleMenuButtonHeld;
-(BOOL)handleMenuButtonDoubleTap;
-(BOOL)handleMenuButtonTap;
-(void)animateDeactivation;
-(BOOL)currentlyAnimatingDeactivation;
-(void)willBeginDeactivationForTransitionToApps:(id)apps animated:(BOOL)animated;
-(void)didFinishAnimatingOut;
-(void)didFinishAnimatingIn;
-(id)legibilitySettings;
-(id)effectiveStatusBarStyleRequest;
-(int)effectiveStatusBarStyle;
-(id)statusBarStyleRequest;
-(int)starkStatusBarStyle;
-(int)statusBarStyle;
-(double)autoLockTime;
-(double)autoDimTime;
-(BOOL)managesOwnStatusBarAtActivation;
-(BOOL)allowsEventOnlySuspension;
-(BOOL)expectsFaceContactInLandscape;
-(BOOL)expectsFaceContact;
-(void)setExpectsFaceContact:(BOOL)contact inLandscape:(BOOL)landscape;
-(void)setExpectsFaceContact:(BOOL)contact;
-(BOOL)orientationChangedEventsEnabled;
-(void)setOrientationChangedEventsEnabled:(BOOL)enabled;
-(id)_basicDescription;
-(void)deactivate;
-(int)interfaceOrientationForActivation;
-(void)activate;
-(int)statusBarStyleOverridesToCancel;
-(void)displayDidDisappear;
-(float)finalAlpha;
-(BOOL)showsSpringBoardStatusBar;
-(BOOL)undimsDisplay;
-(BOOL)allowsStackingOfAlert:(id)alert;
-(void)removeObjectForKey:(id)key;
-(id)objectForKey:(id)key;
-(void)setObject:(id)object forKey:(id)key;
-(id)alertDisplayViewWithSize:(CGSize)size;
-(void)removeBackgroundStyleWithAnimationFactory:(id)animationFactory;
-(void)setBackgroundStyle:(int)style withAnimationFactory:(id)animationFactory force:(BOOL)force;
-(void)setBackgroundStyle:(int)style withAnimationFactory:(id)animationFactory;
-(int)customBackgroundStyle;
-(BOOL)wantsCustomBackgroundStyleForAllWallpaperVariants;
-(BOOL)wantsCustomBackgroundStyle;
-(BOOL)isWallpaperTunnelActive;
-(void)setWallpaperTunnelActive:(BOOL)active;
-(void)applyStateSettings:(id)settings;
-(id)objectForStateSetting:(unsigned)stateSetting;
-(void)setObject:(id)object forStateSetting:(unsigned)stateSetting;
-(BOOL)boolForStateSetting:(unsigned)stateSetting;
-(int)flagForStateSetting:(unsigned)stateSetting;
-(void)setFlag:(int)flag forStateSetting:(unsigned)stateSetting;
-(void)clearStateSettings;
-(void)applyDeactivationSettings:(id)settings;
-(id)objectForDeactivationSetting:(unsigned)deactivationSetting;
-(void)setObject:(id)object forDeactivationSetting:(unsigned)deactivationSetting;
-(BOOL)boolForDeactivationSetting:(unsigned)deactivationSetting;
-(int)flagForDeactivationSetting:(unsigned)deactivationSetting;
-(void)setFlag:(int)flag forDeactivationSetting:(unsigned)deactivationSetting;
-(void)clearDeactivationSettings;
-(void)applyActivationSettings:(id)settings;
-(id)objectForActivationSetting:(unsigned)activationSetting;
-(void)setObject:(id)object forActivationSetting:(unsigned)activationSetting;
-(BOOL)boolForActivationSetting:(unsigned)activationSetting;
-(int)flagForActivationSetting:(unsigned)activationSetting;
-(void)setFlag:(int)flag forActivationSetting:(unsigned)activationSetting;
-(void)clearActivationSettings;
-(id)copyDisplaySettings;
-(void)dismissAlert;
-(void)clearDisplay;
-(id)display;
-(void)didRotateFromInterfaceOrientation:(int)interfaceOrientation;
-(void)willAnimateRotationToInterfaceOrientation:(int)interfaceOrientation duration:(double)duration;
-(void)willRotateToInterfaceOrientation:(int)interfaceOrientation duration:(double)duration;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(void)viewDidDisappear:(BOOL)view;
-(void)viewWillDisappear:(BOOL)view;
-(void)viewDidAppear:(BOOL)view;
-(void)viewWillAppear:(BOOL)view;
-(void)loadView;
-(BOOL)wantsFullScreenLayout;
-(id)_screen;
-(void)_setTargetScreen:(id)screen;
-(void)dealloc;
-(id)init;
-(BOOL)isRemote;
-(BOOL)matchesInCallUIService;
-(BOOL)matchesAnyInCallService;
-(BOOL)matchesRemoteAlertService:(id)service options:(id)options;
-(id)effectiveViewController;
@end

