/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "SBAlertDelegate.h"
#import "FBWindowContextManagerDelegate.h"
#import "FBWindowContextManagerObserver.h"
#import "SpringBoard-Structs.h"

@class NSString, NSMutableSet, SBAlertWindow, FBScene, NSMutableArray, SBDisableActiveInterfaceOrientationChangeAssertion, NSMapTable, UIScreen;
@protocol SBAlertManagerDelegate;

__attribute__((visibility("hidden")))
@interface SBAlertManager : XXUnknownSuperclass <SBAlertDelegate, FBWindowContextManagerDelegate, FBWindowContextManagerObserver> {
	UIScreen* _screen;
	CGRect _windowFrame;
	FBScene* _alertScene;
	SBAlertWindow* _alertWindow;
	SBAlertWindow* _deferredAlertWindow;
	NSMutableArray* _alerts;
	NSMapTable* _observers;
	NSMutableSet* _removalPendingAlerts;
	NSMapTable* _alertToAccessoryWrappersMap;
	BOOL _deactivatingAllAlerts;
	id<SBAlertManagerDelegate> _delegate;
	SBDisableActiveInterfaceOrientationChangeAssertion* _orientationLockAssertion;
	struct {
		unsigned deactivateDismissed : 1;
		unsigned newWindow : 1;
	} _delegateFlags;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(readonly, assign, nonatomic) SBAlertWindow* alertWindow;
@property(assign, nonatomic) id<SBAlertManagerDelegate> delegate;
-(void)windowContextManagerDidStopTrackingContexts:(id)windowContextManager;
-(void)windowContextManagerWillStartTrackingContexts:(id)windowContextManager;
-(BOOL)windowContextManager:(id)manager shouldAddContext:(id)context;
-(void)alertWantsToForceWallpaperTunnelUpdate:(id)forceWallpaperTunnelUpdate;
-(void)alertIsReadyToBeRemovedFromView:(id)view;
-(void)alertIsReadyToBeDeactivated:(id)beDeactivated;
-(void)alertWillDismiss:(id)alert;
-(void)alert:(id)alert requestsBackgroundStyleChangeWithAnimationFactory:(id)animationFactory;
-(void)_disablePortraitOrientationLockIfPossibleForAlert:(id)alert;
-(void)_disablePortraitOrientationLock;
-(void)_enablePortraitOrientationLock;
-(BOOL)_needsPortraitOrientationLockForAlert:(id)alert;
-(void)_makeAlertWindowOpaque:(BOOL)opaque;
-(void)_resetAlertWindowOpacity;
-(id)_hostedAccessoryViewsForAlert:(id)alert;
-(void)_hideHostedAccessoryViewsForAlert:(id)alert;
-(void)_stopHostingAccessoryWindowsForDeactivatingAlert:(id)deactivatingAlert;
-(void)_hostAccessoryWindowsForActivatingAlert:(id)activatingAlert;
-(id)_accessoryWrapperForAlert:(id)alert withWindow:(id)window hostRequester:(id)requester;
-(void)_removeFromView:(id)view oldAlertIndex:(unsigned)index;
-(void)_deactivate:(id)deactivate;
-(void)_activate:(id)activate;
-(id)_createAlertWindowForAlert:(id)alert;
-(void)removeObserver:(id)observer;
-(void)addObserver:(id)observer;
-(void)applicationFinishedAnimatingBeneathAlert;
-(void)applicationWillAnimateActivation;
-(void)deactivateAlertsAfterLaunch;
-(void)setAlertsShouldDeactivateAfterLaunch;
-(void)deactivateAll;
-(void)deactivate:(id)deactivate;
-(void)activate:(id)activate;
-(id)allAlerts;
-(BOOL)containsAlert:(id)alert;
-(id)stackedAlertsIncludingActiveAlert:(BOOL)alert;
-(BOOL)hasStackedAlerts;
-(id)activeAlert;
-(id)contextHostManager;
-(id)screen;
-(void)dealloc;
-(id)init;
-(id)initWithScreen:(id)screen delegate:(id)delegate;
@end

