/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol SBAlertDelegate <NSObject>
-(void)alertWantsToForceWallpaperTunnelUpdate:(id)forceWallpaperTunnelUpdate;
-(void)alertIsReadyToBeRemovedFromView:(id)view;
-(void)alertIsReadyToBeDeactivated:(id)beDeactivated;
-(void)alertWillDismiss:(id)alert;
-(void)alert:(id)alert requestsBackgroundStyleChangeWithAnimationFactory:(id)animationFactory;
@end

