/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBAlert.h"
#import "SpringBoard-Structs.h"

@class UIViewController;

__attribute__((visibility("hidden")))
@interface SBAlertAdapter : SBAlert {
	UIViewController* _effectiveViewController;
}
-(id)viewControllerForSupportedInterfaceOrientations;
-(id)effectiveViewController;
-(void)setDisplay:(id)display;
-(id)_basicDescription;
-(id)alertDisplayViewWithSize:(CGSize)size;
-(id)display;
-(void)alertWindow:(id)window resizedFromContentFrame:(CGRect)contentFrame toContentFrame:(CGRect)contentFrame3;
-(unsigned)supportedInterfaceOrientations;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(BOOL)shouldAutorotate;
-(BOOL)shouldAutomaticallyForwardRotationMethods;
-(BOOL)shouldAutomaticallyForwardAppearanceMethods;
-(void)setView:(id)view;
-(void)dealloc;
-(id)initWithViewController:(id)viewController;
@end

