/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "SBAppSwitcherPageContentView.h"

@class SBZoomView, SBAppSwitcherStatusBarViewCache, UIView, NSString, SBWallpaperEffectView;
@protocol SBAppSwitcherCacheVended;

__attribute__((visibility("hidden")))
@interface SBAppSwitcherContinuityAppView : XXUnknownSuperclass <SBAppSwitcherPageContentView> {
	UIView* _containerView;
	SBWallpaperEffectView* _wallpaperView;
	UIView<SBAppSwitcherCacheVended>* _fakeStatusBarView;
	SBAppSwitcherStatusBarViewCache* _statusBarCache;
	NSString* _bundleIdentifier;
	SBZoomView* _zoomView;
	int _orientation;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(assign, nonatomic) int orientation;
-(void)_viewDismissing:(id)dismissing;
-(void)_willAnimateDismiss:(id)dismiss;
-(CGAffineTransform)_rotationTransformForOrientation:(int)orientation;
-(void)layoutSubviews;
-(CGSize)sizeThatFits:(CGSize)fits;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame bundleIdentifier:(id)identifier;
@end

