/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "SBPeopleScrollViewItemView.h"
#import "UIActionSheetDelegate.h"

@class SBMaskEndGradientClippingView, SBAppSwitcherPeopleViewController, _UILegibilitySettings, UIView, NSString, SBScrollViewItemWrapper, UIScrollView, SBAppSwitcherPeopleContactView;

__attribute__((visibility("hidden")))
@interface SBAppSwitcherPeopleContactContainer : XXUnknownSuperclass <UIActionSheetDelegate, SBPeopleScrollViewItemView> {
	SBAppSwitcherPeopleContactView* _contactView;
	unsigned _presentedSheetActionType;
	UIView* _actionButtonClippingContainer;
	UIScrollView* _actionButtonScrollView;
	UIView* _maskView;
	SBMaskEndGradientClippingView* _maskRightGradient;
	SBMaskEndGradientClippingView* _maskLeftGradient;
	SBScrollViewItemWrapper* _itemWrapper;
	SBAppSwitcherPeopleViewController* _peopleController;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(assign, nonatomic) SBAppSwitcherPeopleViewController* peopleController;
@property(retain, nonatomic) _UILegibilitySettings* legibilitySettings;
@property(retain, nonatomic) SBScrollViewItemWrapper* itemWrapper;
+(CGSize)layoutSizeOfActionButtonArrayContentSizeForItem:(id)item monogramSize:(float)size compact:(BOOL)compact forSize:(CGSize)size4;
+(CGSize)layoutSizeOfExpandedActionButtonScrollViewForItem:(id)item monogramSize:(float)size compact:(BOOL)compact forSize:(CGSize)size4;
+(CGSize)layoutSizeOfActionButtonForItem:(id)item action:(id)action monogramSize:(float)size compact:(BOOL)compact forSize:(CGSize)size5;
+(CGSize)preferredLayoutSizeForItem:(id)item monogramSize:(float)size compact:(BOOL)compact expanded:(BOOL)expanded forSize:(CGSize)size5;
+(float)actionButtonItemReferenceSize;
-(void)_tappedContactActionButton:(id)button;
-(void)tappedGestureRecognizerOnContactContainer:(id)container;
-(void)layoutSubviews;
-(void)_layoutMaskView;
-(void)_removeActionButtons;
-(void)_addActionButtons;
-(void)_updateViewContents;
-(void)_removeClippingContainerMask;
-(void)_configureClippingContainerMask;
-(void)_removeActionButtonsScrollView;
-(void)_configureActionButtonScrollView;
-(void)didCollapseItem;
-(void)willExpandItem;
-(id)_contactItem;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame peopleController:(id)controller;
@end

