/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class FBSSceneClientSettings, FBSDisplay, NSString, SBDisplayLayout, UIMutableApplicationSceneSettings, SBApplication, UIApplicationSceneTransitionContext;
@protocol UIApplicationSceneClientSettings;

__attribute__((visibility("hidden")))
@interface SBApplicationSceneUpdateTransaction : XXUnknownSuperclass {
	SBApplication* _app;
	FBSDisplay* _display;
	SBDisplayLayout* _layout;
	NSString* _sceneIdentifier;
	UIMutableApplicationSceneSettings* _settings;
	UIApplicationSceneTransitionContext* _transitionContext;
	FBSSceneClientSettings<UIApplicationSceneClientSettings>* _clientSettings;
	BOOL _suspendedActivation;
}
@property(readonly, retain, nonatomic) UIMutableApplicationSceneSettings* sceneSettings;
@property(retain, nonatomic) NSString* sceneIdentifier;
-(id)_customizedDescriptionProperties;
-(void)_performSynchronizedCommit:(id)commit;
-(void)_willAddChildTransaction:(id)transaction;
-(void)dealloc;
-(id)initWithApplication:(id)application display:(id)display layout:(id)layout;
@end

