/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBAppSwitcherPageContentView.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "SpringBoard-Structs.h"

@class SBWallpaperEffectView, SBZoomableCrossfadeView, UIImageView, NSString, SBAppSwitcherSettings, UIView, SBSnapshotImageInfo, UIImage, SBAppSwitcherStatusBarViewCache, SBApplication, SBDisplayItem, NSObject;
@protocol SBAppSwitcherCacheVended, OS_dispatch_queue;

__attribute__((visibility("hidden")))
@interface SBAppSwitcherSnapshotView : XXUnknownSuperclass <SBAppSwitcherPageContentView> {
	SBDisplayItem* _displayItem;
	SBApplication* _application;
	UIView* _containerView;
	SBAppSwitcherSettings* _settings;
	SBWallpaperEffectView* _wallpaperEffectView;
	SBSnapshotImageInfo* _snapshotImageInfo;
	UIImageView* _snapshotImageView;
	CGSize _imageSize;
	SBZoomableCrossfadeView* _updateCrossfadeView;
	SBZoomableCrossfadeView* _zoomUpCrossfadeView;
	UIImageView* _zoomUpSnapshotView;
	CGSize _zoomUpImageSize;
	UIImage* _deferredUpdateImage;
	SBAppSwitcherStatusBarViewCache* _statusBarCache;
	UIView<SBAppSwitcherCacheVended>* _statusBar;
	BOOL _isVisible;
	BOOL _simplifyForMotion;
	BOOL _invalidated;
	BOOL _needsZoomFilter;
	BOOL _loadedImage;
	BOOL _needsZoomUpImage;
	int _appSnapshotUpdatedSequenceID;
	NSObject<OS_dispatch_queue>* _snapshotQueue;
	BOOL _shouldTransitionToDefaultPng;
	int _orientation;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(assign) BOOL invalidated;
@property(retain, nonatomic) UIImage* deferredUpdateImage;
@property(retain, nonatomic) SBZoomableCrossfadeView* updateCrossfadeView;
@property(retain, nonatomic) SBSnapshotImageInfo* snapshotImageInfo;
@property(assign, nonatomic) BOOL shouldTransitionToDefaultPng;
@property(assign, nonatomic) int orientation;
@property(readonly, copy, nonatomic) SBDisplayItem* displayItem;
+(id)_fallbackDefaultBackgroundColor;
+(id)appSwitcherSnapshotViewForDisplayItem:(id)displayItem orientation:(int)orientation loadAsync:(BOOL)async withQueue:(id)queue statusBarCache:(id)cache;
-(void)_viewDismissing:(id)dismissing;
-(void)_viewPresenting:(id)presenting;
-(void)_updateStatusbarTranslucency;
-(void)_updateTranslucency;
-(id)_snapshotImageForImageInfo:(id)imageInfo downscaledIfAvailable:(BOOL)available downscaledWasAvailableOut:(out BOOL*)anOut;
-(CGImageRef)_cgImageForSnapshotInfo:(id)snapshotInfo downscaled:(BOOL)downscaled;
-(id)_cachedImageForImageInfos:(id)imageInfos downscaled:(BOOL)downscaled foundInfo:(out id*)info;
-(CGAffineTransform)_rotationTransformForOrientation;
-(int)_containerOrientation;
-(CGRect)_snapshotFrame;
-(void)_snapshotImageLoaded:(CGImageRef)loaded withInfo:(id)info downscaled:(BOOL)downscaled;
-(void)_loadImageAsyncFromSnapshotInfo:(id)snapshotInfo;
-(void)_loadImageAsyncBodySnapshotInfo:(id)info displayItem:(id)item;
-(BOOL)_queue_keepGoing;
-(CGImageRef)_queue_createDecodedImageIfPossible:(CGImageRef)possible;
-(id)_snapshotInfos;
-(id)_snapshotInfoForDefaultPNGWithLaunchOrientation:(int)launchOrientation;
-(id)_snapshotInfoForDefaultPNG;
-(id)_snapshotInfoForSnapshotFromInfos:(id)infos;
-(id)_cachedSnapshotForSnapshotInfos:(id)snapshotInfos downscaled:(BOOL)downscaled foundInfo:(out id*)info;
-(id)_snapshotName;
-(void)_loadSnapshotAsync;
-(void)_loadZoomUpSnapshotSync;
-(void)_loadSnapshotSync;
-(id)_imageFromSnapshotInfos:(id)snapshotInfos forZoomUp:(BOOL)zoomUp loadedImageInfoOut:(out id*)anOut loadedDownscaledOut:(out BOOL*)anOut4;
-(void)invalidate;
-(void)setOrientation:(int)orientation orientationBehavior:(int)behavior;
-(void)layoutSubviews;
-(void)_layoutContainer;
-(void)_crossfadeToNewSnapshotImage:(id)newSnapshotImage;
-(void)_crossfadeToZoomUpViewIfNecessary;
-(void)_snapshotChanged:(id)changed;
-(void)respondToBecomingInvisibleIfNecessary;
-(void)prepareToBecomeVisibleIfNecessary;
-(void)unsimplifyAfterMotion;
-(void)simplifyForMotion;
-(void)_layoutStatusBar;
-(CGSize)sizeThatFits:(CGSize)fits;
-(void)dealloc;
-(id)initWithDisplayItem:(id)displayItem application:(id)application orientation:(int)orientation async:(BOOL)async withQueue:(id)queue statusBarCache:(id)cache;
-(id)initWithFrame:(CGRect)frame;
@end

