/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"

@protocol SBAppSwitcherPeopleDataSourceConsumer;

@protocol SBAppSwitcherPeopleDataSource <NSObject>
@property(assign, nonatomic) id<SBAppSwitcherPeopleDataSourceConsumer> consumer;
-(void)purgeCaches;
-(id)silhouetteMonogramOfSize:(float)size;
-(id)existingCachedMonogramImageForPersonID:(int)personID ofSize:(float)size outIsMask:(BOOL*)mask;
-(void)cachedMonogramImageForPersonID:(int)personID ofSize:(float)size generatingIfNecessaryWithResult:(id)result;
-(void)updateIfNecessary;
-(id)optionalEmptyPlaceholderStringForSection:(unsigned)section;
-(id)titleForSection:(unsigned)section;
-(id)contactItemForIndexPath:(id)indexPath;
-(unsigned)numberOfContactsInSection:(unsigned)section;
-(unsigned)numberOfSections;
@end

