/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBUIAnimationControllerGroupObserver.h"
#import "SBToAppWorkspaceTransaction.h"

@class NSString, SBUIAnimationController, SBApplication;

__attribute__((visibility("hidden")))
@interface SBAppToAppWorkspaceTransaction : SBToAppWorkspaceTransaction <SBUIAnimationControllerGroupObserver> {
	SBApplication* _fromApp;
	SBUIAnimationController* _animationController;
	BOOL _animatedActivation;
	BOOL _animatedDeactivation;
	BOOL _deactivatingAppFromAppToAppGesture;
	BOOL _appQuitFromSwitcher;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(retain, nonatomic) SBApplication* fromApp;
-(void)animationControllerDidFinishAnimation:(id)animationController;
-(void)animationControllerDidRevealApplication:(id)animationController;
-(void)animationController:(id)controller willBeginAnimation:(BOOL)animation;
-(id)_setupAnimationFrom:(id)from to:(id)to;
-(void)_didComplete;
-(void)_didInterruptWithReason:(id)reason;
-(BOOL)_canBeInterrupted;
-(void)_endAnimation;
-(void)_handleApplicationUpdateScenesTransactionFailed:(id)failed;
-(void)_handleApplicationDidNotChange:(id)_handleApplication;
-(void)_kickOffActivation;
-(void)_begin;
-(void)_beginAnimation;
-(void)_setupAnimation;
-(void)_synchronizeWithSceneUpdates;
-(id)_setupMilestonesFrom:(id)from to:(id)to;
-(BOOL)shouldDismissSwitcher;
-(BOOL)shouldAnimateOrientationChangeOnCompletion;
-(BOOL)shouldPerformToAppStateCleanupOnCompletion;
-(BOOL)shouldRestoreSpringBoardContentOnCleanup;
-(BOOL)shouldToggleSpringBoardStatusBarOnCleanup;
-(void)dealloc;
-(id)initWithAlertManager:(id)alertManager exitedApp:(id)app;
-(id)initWithAlertManager:(id)alertManager from:(id)from to:(id)to withResult:(id)result;
@end

