/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBAppSwitcherPeopleButtonAndLabelView.h"


__attribute__((visibility("hidden")))
@interface SBAppSwitcherPeopleContactView : SBAppSwitcherPeopleButtonAndLabelView {
}
+(float)_layoutLabelFontSizeCompact:(BOOL)compact;
+(float)_layoutLabelVerticalPaddingCompact:(BOOL)compact;
+(CGSize)preferredLayoutSizeForMonogramSize:(float)monogramSize compact:(BOOL)compact;
@end

