/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBNewsstandItemIconView.h"
#import "SpringBoard-Structs.h"


__attribute__((visibility("hidden")))
@interface SBAppSwitcherNewsstandItemIconView : SBNewsstandItemIconView {
}
+(float)_labelHeight;
+(int)_defaultIconFormat;
-(float)_labelVerticalOffset;
-(CGRect)_frameForLabelAccessoryViewWithLabelFrame:(CGRect)labelFrame;
-(CGRect)_frameForLabel;
-(id)initWithFrame:(CGRect)frame;
@end

