/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "SBLeafIconDataSource.h"
#import "FBApplicationPlaceholderObserver.h"

@class NSString, FBApplicationPlaceholder, NSMutableDictionary, NSMutableSet;

__attribute__((visibility("hidden")))
@interface SBApplicationPlaceholder : XXUnknownSuperclass <FBApplicationPlaceholderObserver, SBLeafIconDataSource> {
	FBApplicationPlaceholder* _placeholderProxy;
	NSString* _applicationBundleID;
	NSString* _applicationDisplayName;
	double _fractionProgress;
	BOOL _installing;
	BOOL _isNewsstand;
	BOOL _observingKVO;
	unsigned _installType;
	BOOL _invalidated;
	NSMutableDictionary* _generatedIconImagesByKey;
	NSMutableSet* _formatsPendingGeneration;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(copy, nonatomic) NSString* applicationDisplayName;
@property(copy, nonatomic) NSString* applicationBundleID;
@property(retain, nonatomic) FBApplicationPlaceholder* placeholderProxy;
+(id)backgroundQueue;
-(BOOL)icon:(id)icon launchFromLocation:(int)location;
-(BOOL)iconAllowsLaunch:(id)launch;
-(BOOL)iconCompleteUninstall:(id)uninstall;
-(BOOL)iconAllowsUninstall:(id)uninstall;
-(BOOL)iconIsBeta:(id)beta;
-(BOOL)iconIsRecentlyUpdated:(id)updated;
-(id)iconFormattedAccessoryString:(id)string;
-(id)iconBadgeNumberOrString:(id)string;
-(int)iconAccessoryType:(id)type;
-(BOOL)iconProgressIsPaused:(id)paused;
-(float)iconProgressPercent:(id)percent;
-(int)iconProgressState:(id)state;
-(BOOL)iconAppearsInNewsstand:(id)newsstand;
-(BOOL)iconCanTightenLabel:(id)label;
-(BOOL)iconCanEllipsizeLabel:(id)label;
-(id)icon:(id)icon defaultImageWithFormat:(int)format;
-(id)icon:(id)icon imageWithFormat:(int)format;
-(unsigned)iconPriority:(id)priority;
-(id)iconDisplayName:(id)name;
-(void)_reloadThumbnailImage;
-(void)_generatePendingIconFormats;
-(void)_generateIconImageWithFormat:(int)format;
-(id)_iconImageKeyForBundleID:(id)bundleID format:(int)format;
-(int)_newsstandImageOptions;
-(id)_defaultIconImageWithFormat:(int)format;
-(id)_getOrGenerateIconImageWithFormat:(int)format;
-(void)placeholderDidChangeSignificantly:(id)placeholder;
-(void)placeholderInstallPhaseDidChange:(id)placeholderInstallPhase;
-(void)placeholderInstallStateDidChange:(id)placeholderInstallState;
-(void)placeholderPausabilityDidChange:(id)placeholderPausability;
-(void)placeholderCancellabilityDidChange:(id)placeholderCancellability;
-(void)placeholderPercentCompleteDidChange:(id)placeholderPercentComplete;
-(void)_progressChanged;
-(BOOL)_shouldDisplayAppName;
-(id)_downloadingLabel;
-(void)_prioritize;
-(void)cancel;
-(void)resume;
-(void)pause;
-(BOOL)isNewsstand;
-(BOOL)isContentRestricted;
-(BOOL)isInstalling;
-(BOOL)isDownloading;
-(BOOL)isCancelable;
-(BOOL)isPausable;
-(BOOL)isFailed;
-(BOOL)isPaused;
-(BOOL)isActive;
-(BOOL)isDone;
-(unsigned)installType;
-(id)fetchIconImageWithFormat:(int)format;
-(void)iconChanged;
-(BOOL)isEqual:(id)equal;
-(void)invalidate;
-(void)dealloc;
-(id)initWithPlaceholderProxy:(id)placeholderProxy;
@end

