/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */



@protocol SBApplicationPlaceholderLifecycleObserver
-(void)applicationPlaceholdersNetworkUsageChanged:(BOOL)changed;
-(void)applicationPlaceholdersInstalled:(id)installed;
-(void)applicationPlaceholdersCancelled:(id)cancelled;
-(void)applicationPlaceholdersAdded:(id)added;
@end

