/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBAppSwitcherPeopleDataSource.h"
#import "SBAppSwitcherPeopleAbstractDataSource.h"

@class NSString, NSMutableArray, NSMutableDictionary;
@protocol SBAppSwitcherPeopleDataSourceConsumer;

__attribute__((visibility("hidden")))
@interface SBAppSwitcherTwoSectionFakeDataSource : SBAppSwitcherPeopleAbstractDataSource <SBAppSwitcherPeopleDataSource> {
	NSMutableArray* _sectionOne;
	NSMutableArray* _sectionTwo;
	NSMutableDictionary* _personIDsToColors;
	int _maxPersonID;
}
@property(assign, nonatomic) id<SBAppSwitcherPeopleDataSourceConsumer> consumer;
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
-(id)optionalEmptyPlaceholderStringForSection:(unsigned)section;
-(id)titleForSection:(unsigned)section;
-(id)contactItemForIndexPath:(id)indexPath;
-(unsigned)numberOfContactsInSection:(unsigned)section;
-(unsigned)numberOfSections;
-(void)purgeCaches;
-(id)existingCachedMonogramImageForPersonID:(int)personID ofSize:(float)size outIsMask:(BOOL*)mask;
-(void)cachedMonogramImageForPersonID:(int)personID ofSize:(float)size generatingIfNecessaryWithResult:(id)result;
-(BOOL)isImageMaskForPersonID:(int)personID ofSize:(float)size;
-(id)silhouetteMonogramOfSize:(float)size;
-(id)_rectOfColor:(id)color size:(float)size;
-(void)_insertOneRecentPersonAndDeleteOneAtTheEnd;
-(void)_swapColorOfOneRecentPerson;
-(void)_fillInSectionArrays;
-(id)_randomColor;
-(void)dealloc;
-(id)init;
@end

