/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBFileLogger.h"


__attribute__((visibility("hidden")))
@interface SBBannerLogger : SBFileLogger {
}
-(id)logPrefixForCategory:(id)category destination:(unsigned)destination;
-(id)logPreferenceName;
-(void)_setEnabled:(BOOL)enabled;
-(id)name;
-(BOOL)isEnabled;
@end

