/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSArray;
@protocol SBBannerButtonViewControllerDelegate;

__attribute__((visibility("hidden")))
@interface SBBannerButtonViewController : XXUnknownSuperclass {
	NSArray* _buttons;
	id<SBBannerButtonViewControllerDelegate> _delegate;
}
@property(assign, nonatomic) id<SBBannerButtonViewControllerDelegate> delegate;
-(void)_buttonPressed:(id)pressed;
-(id)_buttonForActionTitle:(id)actionTitle;
-(id)_buttonView;
-(CGSize)preferredContentSize;
-(void)setButtonTitles:(id)titles;
-(void)loadView;
-(void)dealloc;
@end

