/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, UIFetchContentInBackgroundAction;

__attribute__((visibility("hidden")))
@interface SBBackgroundFetchExternalRequest : XXUnknownSuperclass {
	UIFetchContentInBackgroundAction* _action;
	int _sequenceNumber;
	NSString* _bundleID;
}
@property(copy, nonatomic) NSString* bundleID;
@property(assign, nonatomic) int sequenceNumber;
@property(retain, nonatomic) UIFetchContentInBackgroundAction* action;
-(void)execute;
-(void)dealloc;
-(id)initForBundleID:(id)bundleID;
@end

