/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "UIViewControllerAnimatedTransitioning.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "SpringBoard-Structs.h"
#import "SBBulletinWindowClient.h"
#import "NCInteractiveNotificationHostDelegate.h"
#import "SBBannerButtonViewControllerDelegate.h"
#import "NCBannerAccessoryHostViewControllerDelegate.h"
#import "SBMotionGestureObserver.h"
#import "UIViewControllerTransitioningDelegate.h"

@class SBBannerContextView, NCInteractiveNotificationHostViewController, NCBannerAccessoryHostViewController, SBBannerContainerView, NCContentHostViewController, SBUIBannerContext, NSString, FBUIApplicationResignActiveAssertion, UIView, UIImage, SBBannerButtonViewController;
@protocol SBBannerContextViewControllerDelegate;

__attribute__((visibility("hidden")))
@interface SBBannerContainerViewController : XXUnknownSuperclass <NCInteractiveNotificationHostDelegate, SBBannerButtonViewControllerDelegate, NCBannerAccessoryHostViewControllerDelegate, SBMotionGestureObserver, SBBulletinWindowClient, UIViewControllerTransitioningDelegate, UIViewControllerAnimatedTransitioning> {
	NCInteractiveNotificationHostViewController* _interactiveViewController;
	NCBannerAccessoryHostViewController* _accessoryViewController;
	NCContentHostViewController* _secondaryContentViewController;
	NCContentHostViewController* _inlayContentViewController;
	SBBannerButtonViewController* _buttonViewController;
	BOOL _notifiedAppeared;
	SBUIBannerContext* _bannerContext;
	SBBannerContainerView* _containerView;
	SBBannerContextView* _bannerContextView;
	FBUIApplicationResignActiveAssertion* _resignActiveAssertion;
	UIView* _backgroundView;
	CGRect _keyboardFrame;
	float _maximumBannerHeight;
	BOOL _pulledDown;
	id<SBBannerContextViewControllerDelegate> _delegate;
	UIImage* _backgroundImage;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(readonly, assign, nonatomic) BOOL showsKeyboard;
@property(readonly, assign, nonatomic, getter=isPulledDown) BOOL pulledDown;
@property(readonly, assign, nonatomic) BOOL canPullDown;
@property(readonly, assign, nonatomic) UIView* backgroundView;
@property(readonly, assign, nonatomic) SBBannerContextView* bannerContextView;
@property(retain, nonatomic) UIImage* backgroundImage;
@property(assign, nonatomic) id<SBBannerContextViewControllerDelegate> delegate;
-(void)animateTransition:(id)transition;
-(double)transitionDuration:(id)duration;
-(id)animationControllerForDismissedController:(id)dismissedController;
-(id)animationControllerForPresentedController:(id)presentedController presentingController:(id)controller sourceController:(id)controller3;
-(void)_keyboardWillChange:(id)_keyboard;
-(id)_bulletin;
-(void)_updateMotionGestureObservation;
-(void)didReceiveRaiseGesture;
-(void)hostViewController:(id)controller didRequestSticky:(BOOL)sticky;
-(void)hostViewControllerDidRequestSticky:(id)hostViewController;
-(void)hostViewControllerDidRequestDismissal:(id)hostViewController;
-(void)buttonViewController:(id)controller didSelectButtonAtIndex:(unsigned)index;
-(void)_removeButtonViewController;
-(void)_setButtonViewController:(id)controller;
-(id)_newbuttonViewController;
-(void)hostViewController:(id)controller didRequestDismissalWithContext:(id)context;
-(void)hostViewControllerDidChangePreferredContentSize:(id)hostViewController;
-(BOOL)requiresKeyWindow;
-(void)bulletinWindowDidRotateFromOrientation:(int)bulletinWindow;
-(void)bulletinWindowIsAnimatingRotationToOrientation:(int)orientation duration:(double)duration;
-(void)bulletinWindowWillRotateToOrientation:(int)bulletinWindow duration:(double)duration;
-(void)_removeInteractiveViewController;
-(void)_setInteractiveViewController:(id)controller;
-(void)_removeInlayContentViewController;
-(void)_setInlayContentViewController:(id)controller;
-(void)_setInlayContentViewWithCompletion:(id)completion;
-(void)_removeSecondaryContentViewController;
-(void)_setSecondaryContentViewController:(id)controller;
-(void)_setSecondaryContentViewWithCompletion:(id)completion;
-(void)_removeAccessoryViewController;
-(void)_setAccessoryViewController:(id)controller;
-(void)_setAccessoryViewWithCompletion:(id)completion;
-(void)_removeChildViewController:(id)controller withTransition:(id)transition;
-(void)_addChildViewController:(id)controller withTransition:(id)transition;
-(void)_removeChildPullDownViewController:(id)controller;
-(void)_addChildPullDownViewController:(id)controller;
-(id)_bannerViewCreatingIfNecessary;
-(BOOL)_hasActions;
-(id)_bannerItem;
-(float)_percentDismissed;
-(void)_updateMaximumPullDownViewHeight;
-(void)_updateMaximumContainerHeightForOrientation:(int)orientation;
-(void)_updateMaximumBannerHeight;
-(void)_updateMaximumHeightsWithOrientation:(int)orientation;
-(void)_updateMaximumHeights;
-(float)_pullDownBottomOverhangHeight;
-(float)_bannerContentHeight;
-(float)_maximumPullDownViewHeight;
-(float)_miniumBannerContentHeight;
-(float)_pullDownViewHeight;
-(float)_preferredPullDownViewHeight;
-(void)_setPullDownViewWithCompletion:(id)completion;
-(CGRect)_bannerFrameForOrientation:(int)orientation;
-(CGRect)_bannerFrame;
-(void)_handleBannerContainerTapGesture:(id)gesture;
-(void)_handleBannerTapGesture:(id)gesture withActionContext:(id)actionContext;
-(void)_handleBannerTapGesture:(id)gesture;
-(void)willPresentFromActionIdentifier:(id)actionIdentifier;
-(void)viewDidAppear:(BOOL)view;
-(float)preferredMaximumHeight;
-(void)setBannerPullDisplacement:(float)displacement;
-(void)_noteDidPullDown;
-(void)setBannerPullPercentage:(float)percentage;
-(void)_loadRemoteViewControllersWithCompletion:(id)completion;
-(void)setBannerContext:(id)context withReplaceReason:(int)replaceReason completion:(id)completion;
-(id)_newBackgroundViewWithFrame:(CGRect)frame;
-(void)loadView;
-(void)invalidate;
-(void)dealloc;
-(id)initWithNibName:(id)nibName bundle:(id)bundle;
@end

