/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBBBBulletinInfo.h"

@class NSString, SBWidgetViewController;

__attribute__((visibility("hidden")))
@interface SBBBWidgetBulletinInfo : SBBBBulletinInfo {
	NSString* _identifier;
	float _preferredViewHeight;
	BOOL _visible;
	struct {
		unsigned isPreferredViewHeightValid : 1;
	} _widgetBulletinInfoFlags;
}
@property(assign, nonatomic) float preferredViewHeight;
@property(readonly, assign, nonatomic) SBWidgetViewController* representedWidget;
-(void)populateReusableView:(id)view;
-(float)heightForReusableViewForBulletinViewController:(id)bulletinViewController layoutMode:(int)mode bulletinLocation:(int)location;
-(id)reusableViewIdentifier;
-(Class)reusableViewClass;
-(id)originalSectionIdentifier;
-(id)identifier;
-(id)widgetIdentifier;
-(id)representedBulletin;
-(void)dealloc;
@end

