/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString;

__attribute__((visibility("hidden")))
@interface SBBoundLayoutConstraint : XXUnknownSuperclass {
	id _object;
	NSString* _keyPath;
}
@property(copy, nonatomic) NSString* keyPath;
@property(retain, nonatomic) id object;
+(id)constraintWithItem:(id)item attribute:(int)attribute relatedBy:(int)by toItem:(id)item4 attribute:(int)attribute5 multiplier:(float)multiplier constantObject:(id)object keyPath:(id)path;
-(void)observeValueForKeyPath:(id)keyPath ofObject:(id)object change:(id)change context:(void*)context;
-(void)_boundValueDidChange;
-(void)bindConstantToObject:(id)object keyPath:(id)path;
-(void)dealloc;
@end

