/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBLeafIcon.h"
#import "SpringBoard-Structs.h"

@class UIWebClip, NSURL, SBBookmark;

__attribute__((visibility("hidden")))
@interface SBBookmarkIcon : SBLeafIcon {
	SBBookmark* _bookmark;
}
@property(readonly, retain, nonatomic) NSURL* launchURL;
@property(readonly, retain, nonatomic) UIWebClip* webClip;
-(BOOL)isBookmarkIcon;
-(id)folderFallbackTitle;
-(id)folderTitleOptions;
-(id)uninstallAlertCancelTitle;
-(id)uninstallAlertConfirmTitle;
-(id)uninstallAlertBody;
-(id)uninstallAlertTitle;
-(id)matchedWebApplication;
-(id)copyWithZone:(NSZone*)zone;
-(void)dealloc;
-(id)initWithBookmark:(id)bookmark;
@end

