/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "SBBulletinBusyClient.h"
#import "BBObserverDelegate.h"

@class NSString, NSMutableArray, BBObserver, NSMutableDictionary, NSMutableSet;

__attribute__((visibility("hidden")))
@interface SBBulletinSoundController : XXUnknownSuperclass <BBObserverDelegate, SBBulletinBusyClient> {
	BBObserver* _observer;
	NSMutableArray* _blockQueue;
	NSMutableDictionary* _playingSounds;
	NSMutableSet* _internalBulletinsWePlayedSoundsFor;
	NSMutableSet* _bulletinsRequiringExplicitKill;
	BOOL _deviceIsLocked;
	BOOL _quietModeEnabled;
	unsigned _quietModeState;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
+(id)sharedInstanceIfExists;
+(id)sharedInstance;
+(id)_sharedInstanceCreateIfNecessary:(BOOL)necessary;
-(void)bulletinWindowStoppedBeingBusy;
-(void)observer:(id)observer noteServerConnectionStateChanged:(BOOL)changed;
-(void)observer:(id)observer noteInvalidatedBulletinIDs:(id)ids;
-(void)observer:(id)observer noteAlertBehaviorOverrideStateChanged:(unsigned)changed;
-(void)observer:(id)observer noteAlertBehaviorOverridesChanged:(unsigned)changed;
-(void)observer:(id)observer removeBulletin:(id)bulletin;
-(void)observer:(id)observer addBulletin:(id)bulletin forFeed:(unsigned)feed playLightsAndSirens:(BOOL)sirens withReply:(id)reply;
-(void)_enqueueBlock:(id)block forBulletin:(id)bulletin;
-(BOOL)_shouldHonorPlaySoundRequestForBulletin:(id)bulletin;
-(void)_hardwareButtonPressed:(id)pressed;
-(BOOL)_playSoundForBulletin:(id)bulletin playedInternally:(BOOL)internally;
-(void)_stopSoundWithID:(id)anId internalOnly:(BOOL)only;
-(unsigned)quietModeState;
-(BOOL)quietModeEnabled;
-(void)killSounds;
-(void)killSoundForBulletin:(id)bulletin;
-(BOOL)playSoundForBulletin:(id)bulletin;
-(void)dealloc;
-(id)init;
@end

