/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBBulletinAlertHandlerRegistry.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "_UISettingsKeyObserver.h"

@class NSString, SBAlertItemsSettings, NSMutableDictionary;

@protocol SBBulletinAlertHandlerRegistry
-(void)addAlertHandler:(id)handler forSection:(id)section;
@end

__attribute__((visibility("hidden")))
@interface SBBulletinAlertHandlerRegistry : XXUnknownSuperclass <_UISettingsKeyObserver, SBBulletinAlertHandlerRegistry> {
	NSMutableDictionary* _handlersBySectionID;
	SBAlertItemsSettings* _settings;
	BOOL _disabled;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
-(void)settings:(id)settings changedValueForKey:(id)key;
-(void)addAlertHandler:(id)handler forSection:(id)section;
-(id)alertHandlersForSection:(id)section;
-(void)dealloc;
-(id)init;
@end

