/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface SBCarDisplaySettings : XXUnknownSuperclass {
	BOOL _animateLockOutModeChanges;
	int _lockOutMode;
}
@property(assign) int lockOutMode;
@property(assign) BOOL animateLockOutModeChanges;
+(id)settingsControllerModule;
-(void)setDefaultValues;
@end

