/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "RadiosPreferencesDelegate.h"
#import "SBCCSettingModule.h"

@class RadiosPreferences;

__attribute__((visibility("hidden")))
@interface SBCCAirplaneModeSetting : SBCCSettingModule <RadiosPreferencesDelegate> {
	RadiosPreferences* _airplaneModeController;
}
+(id)displayName;
+(id)identifier;
-(void)airplaneModeChanged;
-(id)glyphImageForState:(int)state;
-(void)_updateState;
-(BOOL)_toggleState;
-(void)deactivate;
-(void)activate;
-(id)aggdKey;
-(void)dealloc;
@end

