/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBCCSettingModule.h"

@class AVFlashlight, NSObject;
@protocol OS_dispatch_queue;

__attribute__((visibility("hidden")))
@interface SBCCFlashlightSetting : SBCCSettingModule {
	AVFlashlight* _flashlight;
	NSObject<OS_dispatch_queue>* _flashlightQueue;
	BOOL _stayWarm;
	BOOL _flashlightOn;
}
@property(assign, nonatomic, getter=isFlashlightOn) BOOL flashlightOn;
+(BOOL)isSupported:(int)supported;
+(id)displayName;
+(id)identifier;
-(void)observeValueForKeyPath:(id)keyPath ofObject:(id)object change:(id)change context:(void*)context;
-(void)_featureLockStateDidChangeNotification:(id)_featureLockState;
-(void)_deviceBlockStateDidChangeNotification:(id)_deviceBlockState;
-(id)glyphImageForState:(int)state section:(int)section;
-(id)_imageNameForState:(int)state section:(int)section;
-(id)_shortcutImageNameForState:(int)state;
-(id)_settingImageNameForState:(int)state;
-(void)_updateFlashlightPowerState;
-(void)_updateState;
-(BOOL)_enableTorch:(BOOL)torch;
-(BOOL)_toggleState;
-(void)cooldown;
-(void)warmup;
-(void)deactivate;
-(void)_tearDown;
-(void)activate;
-(id)unavailableText;
-(id)statusUpdate;
-(id)aggdKey;
-(id)displayName;
-(void)dealloc;
@end

