/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBCCButtonSectionController.h"


__attribute__((visibility("hidden")))
@interface SBCCQuickLaunchSectionController : SBCCButtonSectionController {
}
+(Class)buttonControllerClass;
-(void)viewWillLayoutSubviews;
-(void)viewDidLoad;
-(CGSize)contentSizeForOrientation:(int)orientation;
-(id)sectionIdentifier;
-(id)init;
@end

