/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBCCShortcutModule.h"


__attribute__((visibility("hidden")))
@interface SBCCCameraShortcut : SBCCShortcutModule {
}
+(id)displayName;
+(id)identifier;
-(id)glyphImageForState:(int)state;
-(BOOL)isRestricted;
-(id)aggdKey;
-(id)init;
@end

