/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBCCShortcutModule.h"


__attribute__((visibility("hidden")))
@interface SBCCPaymentShortcut : SBCCShortcutModule {
}
+(BOOL)enabledByDefault;
+(BOOL)isSupported:(int)supported;
+(id)displayName;
+(id)identifier;
-(void)activateApp;
-(id)glyphImageForState:(int)state;
-(id)aggdKey;
@end

