/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBControlCenterSectionView.h"

@class NSMutableArray, UIScrollView;

__attribute__((visibility("hidden")))
@interface SBCCButtonLayoutView : SBControlCenterSectionView {
	NSMutableArray* _buttons;
	UIScrollView* _scrollView;
	float _interButtonPadding;
	unsigned _buttonStretchThreshold;
	unsigned _buttonShrinkThreshold;
	int _maxButtons;
	UIEdgeInsets _contentEdgeInsets;
}
@property(assign, nonatomic) int maxButtons;
@property(assign, nonatomic) unsigned buttonShrinkThreshold;
@property(assign, nonatomic) unsigned buttonStretchThreshold;
@property(assign, nonatomic) UIEdgeInsets contentEdgeInsets;
@property(assign, nonatomic) float interButtonPadding;
-(void)layoutSubviews;
-(void)_setButtons:(id)buttons;
-(void)_didRemoveButton:(id)button;
-(void)_didAddButton:(id)button;
-(void)resortButtons;
-(void)_resortButtons;
-(void)removeButton:(id)button;
-(void)addButton:(id)button;
-(id)buttons;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
@end

