/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBCCShortcutModule.h"

@class NSDateFormatter, NSString;

__attribute__((visibility("hidden")))
@interface SBCCRecordScreenShortcut : SBCCShortcutModule {
	unsigned long long _sessionToken;
	NSString* _lastRecordingPath;
	NSDateFormatter* _dateFormatter;
}
+(BOOL)enabledByDefault;
+(BOOL)isSupported:(int)supported;
+(id)displayName;
+(id)identifier;
-(id)glyphImageForState:(int)state;
-(id)statusUpdate;
-(BOOL)_toggleState;
-(void)_videoAtPath:(id)path didFinishSavingWithError:(id)error contextInfo:(void*)info;
-(void)_stopRecording;
-(void)_startRecording;
-(void)deactivate;
-(void)activate;
-(void)dealloc;
@end

