/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBCenterAppZoomSettings.h"


__attribute__((visibility("hidden")))
@interface SBCenterAppLaunchSettings : SBCenterAppZoomSettings {
}
-(void)setDefaultValues;
@end

