/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "SBTestRecipe.h"

@class NSString, SBAlertItem;

__attribute__((visibility("hidden")))
@interface SBClientAlertItemTestRecipe : XXUnknownSuperclass <SBTestRecipe> {
	SBAlertItem* _item;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
+(id)title;
-(id)_nextAlertItemToTest;
-(id)_mapsApp;
-(id)_anySUDescriptor;
-(id)_anyIcon;
-(void)handleVolumeDecrease;
-(void)handleVolumeIncrease;
-(void)_dismissCurrentItem;
-(id)_currentAssistantLanguage;
-(void)educationAlertWasDeactivated:(id)deactivated;
-(id)_assistantEducationAlert;
-(id)_chatMMSInformationMissingAlert;
-(id)_chatMMSDelayedDownloadAlert;
-(id)_chatCMSBAlert;
-(id)_chatMessageAlert;
-(id)_chatCarrierSMSAlert;
-(id)_mapsThermalAlert;
-(id)_accessibilityZoomBuddyAlert;
-(id)_accessibilityVoiceOverTouchAlert;
-(id)_wifiTrustAlert;
-(id)_wifiPasswordAlert;
-(id)_wifiIsEnterpriseAlert;
-(id)_wifiErrorAlert;
-(id)_wifiDontAskAlert;
-(id)_wifiBTSSPAlert;
@end

