/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "BBRemoteDataProvider.h"

@class NSDate, NSMutableDictionary, UILocalNotification, NSTimer, BBBulletinRequest, NSString, BBDataProviderProxy;

__attribute__((visibility("hidden")))
@interface SBClockDataProvider : XXUnknownSuperclass <BBRemoteDataProvider> {
	NSTimer* _alarmUpdateTimer;
	BBDataProviderProxy* _dataProviderProxy;
	NSMutableDictionary* _localNotificationsByPublisherBulletinID;
	UILocalNotification* _nextAlarmForToday;
	BBBulletinRequest* _nextTodayAlarmBulletin;
	UILocalNotification* _firstAlarmForTomorrow;
	NSDate* _nextTomorrowFireDate;
	BBBulletinRequest* _nextTomorrowAlarmBulletin;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
+(id)sharedInstance;
-(void)_handleBulletinSnoozeDismissResponse:(id)response;
-(void)_removeBulletinWithPublisherBulletinID:(id)publisherBulletinID;
-(void)_handleBulletinAlarmSnoozeResponse:(id)response;
-(void)_handleBulletinAlarmDismissResponse:(id)response;
-(void)handleBulletinActionResponse:(id)response;
-(id)_actionWithIdentifier:(id)identifier title:(id)title;
-(id)_supplementaryActionsFromAlarmNotification:(id)alarmNotification;
-(id)_snoozeActionFromAlarmNotification:(id)alarmNotification;
-(id)_dismissActionFromSnoozeNotification:(id)snoozeNotification;
-(id)_dismissActionFromAlarmNotification:(id)alarmNotification;
-(id)_alternateActionFromAlarmNotification:(id)alarmNotification;
-(id)_songSoundFromSoundName:(id)soundName;
-(id)_defaultSound;
-(id)_ringtoneSoundFromSoundName:(id)soundName;
-(id)_soundFromNotification:(id)notification;
-(id)_publisherBulletinIDFromNotification:(id)notification;
-(id)_titleFromNotification:(id)notification;
-(id)_timerIDFromNotification:(id)notification;
-(BOOL)_isTimerNotification:(id)notification;
-(id)_alarmIDFromNotification:(id)notification;
-(BOOL)_isAlarmNotification:(id)notification;
-(id)_bulletinForNotification:(id)notification;
-(void)_interruptAudioAndLockDeviceForLocalNotification:(id)localNotification;
-(void)_publishBulletinForLocalNotification:(id)localNotification;
-(void)_handleLocalNotificationDidFire:(id)_handleLocalNotification;
-(id)sortDescriptors;
-(id)bulletinsWithRequestParameters:(id)requestParameters lastCleared:(id)cleared;
-(id)bulletinsFilteredBy:(unsigned)by count:(unsigned)count lastCleared:(id)cleared;
-(int)_sectionSubtypeFromNotification:(id)notification;
-(id)sectionParameters;
-(void)_migrateSectionInfo;
-(id)defaultSectionInfo;
-(id)sectionIdentifier;
-(id)_alarmMessageForNotification:(id)notification withSingleAlarmFormat:(BOOL)singleAlarmFormat;
-(void)_publishAlarmsWithScheduledNotifications:(id)scheduledNotifications;
-(void)_calculateNextTomorrowAlarmAndBulletinWithScheduledNotifications:(id)scheduledNotifications;
-(void)_calculateNextTodayAlarmAndBulletinWithScheduledNotifications:(id)scheduledNotifications;
-(id)_nextAlarmForFeed:(unsigned)feed withNotifications:(id)notifications;
-(void)_snoozedAlarmRefired:(id)refired;
-(id)_bulletinRequestForSnoozedAlarm:(id)snoozedAlarm;
-(void)_handleAlarmSnoozedNotification:(id)notification;
-(id)_bulletinRequestForTimerNotification:(id)timerNotification;
-(void)_publishTimerInScheduledNotifications:(id)scheduledNotifications;
-(id)_scheduledNotifications;
-(void)_handleClockNotificationUpdate:(id)update;
-(void)dealloc;
-(void)dataProviderDidLoad;
-(id)init;
@end

