/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "SBControlCenterObserver.h"

@class SBChevronView, NSString, SBControlCenterContentContainerView, UIView;

__attribute__((visibility("hidden")))
@interface SBControlCenterContainerView : XXUnknownSuperclass <SBControlCenterObserver> {
	UIView* _darkeningView;
	float _revealPercentage;
	SBChevronView* _chevronToTrack;
	BOOL _useMaxDarkness;
	BOOL _animatingDynamically;
	BOOL _adjustingBrightness;
	UIView* _dynamicsContainerView;
	SBControlCenterContentContainerView* _contentContainerView;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(assign, nonatomic, getter=isAdjustingBrightness) BOOL adjustingBrightness;
@property(assign, nonatomic) BOOL animatingDynamically;
@property(assign, nonatomic) float revealPercentage;
@property(readonly, retain, nonatomic) SBControlCenterContentContainerView* contentContainerView;
@property(readonly, retain, nonatomic) UIView* dynamicsContainerView;
-(void)controlCenterDidFinishTransition;
-(void)controlCenterWillFinishTransitionOpen:(BOOL)controlCenter withDuration:(double)duration;
-(void)controlCenterWillBeginTransition;
-(void)controlCenterDidDismiss;
-(void)controlCenterWillPresent;
-(void)updateBackgroundSettings:(id)settings;
-(void)abortAnimatedTransition;
-(id)_contentChevronView;
-(id)_currentBGColor;
-(void)_updateContentFrame;
-(void)_updateDarkeningFrame;
-(void)trackChevronView:(id)view;
-(void)setContentHeight:(float)height;
-(void)layoutSubviews;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
@end

