/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString;

__attribute__((visibility("hidden")))
@interface SBControlCenterButtonSettings : XXUnknownSuperclass {
	BOOL _enabled;
	NSString* _displayName;
	NSString* _identifier;
}
@property(retain, nonatomic) NSString* identifier;
@property(retain, nonatomic) NSString* displayName;
@property(assign, nonatomic) BOOL enabled;
+(id)createWithSettingClass:(Class)settingClass;
+(id)settingsControllerModule;
-(void)setDefaultValues;
@end

