/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class _UISettingsGroup;

__attribute__((visibility("hidden")))
@interface SBControlCenterButtonSectionSettings : XXUnknownSuperclass {
	_UISettingsGroup* _settingsGroup;
}
@property(retain) _UISettingsGroup* settingsGroup;
+(id)supportedButtonModuleClasses;
+(id)buttonModuleClasses;
+(id)settingsControllerModule;
-(id)buttonSortKeyForIdentifier:(id)identifier;
-(BOOL)buttonEnabledForIdentifier:(id)identifier;
-(void)setDefaultValues;
-(Class)buttonSettingsClass;
@end

