/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "SBControlCenterObserver.h"

@class _UIBackdropView, NSString, UIView, SBControlCenterContentView;

__attribute__((visibility("hidden")))
@interface SBControlCenterContentContainerView : XXUnknownSuperclass <SBControlCenterObserver> {
	UIView* _accessibilityBackgroundView;
	UIView* _lighteningView;
	_UIBackdropView* _backdropView;
	SBControlCenterContentView* _contentView;
	float _contentHeight;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(assign) float contentHeight;
@property(retain, nonatomic) SBControlCenterContentView* contentView;
@property(retain, nonatomic) _UIBackdropView* backdropView;
-(void)_accessibilityBackgroundContrastDidChange:(id)_accessibilityBackgroundContrast;
-(void)_updateBackground;
-(void)controlCenterDidFinishTransition;
-(void)controlCenterWillBeginTransition;
-(void)controlCenterDidDismiss;
-(void)controlCenterWillPresent;
-(void)layoutSubviews;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
@end

