/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "SBCoordinatedPresenting.h"
#import "SpringBoard-Structs.h"
#import "SBControlCenterViewControllerDelegate.h"

@class NSHashTable, NSSet, UIImageView, SBChevronView, NSString, NSMutableSet, FBUIApplicationResignActiveAssertion, SBWindow, UIDynamicAnimator, UIView, _UIBackdropView, _UIDynamicValueAnimation, SBControlCenterViewController, SBControlCenterRootView;
@protocol SBPresentingDelegate;

__attribute__((visibility("hidden")))
@interface SBControlCenterController : XXUnknownSuperclass <SBControlCenterViewControllerDelegate, SBCoordinatedPresenting> {
	SBWindow* _window;
	SBControlCenterRootView* _rootView;
	SBControlCenterViewController* _viewController;
	UIImageView* _coveredContentSnapshot;
	UIView* _fullScreenGrabberContainer;
	_UIBackdropView* _fullScreenGrabberBackdrop;
	SBChevronView* _fullScreenChevron;
	FBUIApplicationResignActiveAssertion* _resignActiveAssertion;
	NSMutableSet* _preventDismissalOnLockReasons;
	BOOL _uiLocked;
	NSHashTable* _observers;
	int _orientation;
	BOOL _animatingInitialPresentation;
	BOOL _gotFirstBackdropUpdate;
	BOOL _completingTransitionOpen;
	_UIDynamicValueAnimation* _bounceAnimation;
	UIDynamicAnimator* _animator;
	unsigned _animatorStopCount;
	CGRect _animatorStopFrame;
	BOOL _inGrabberOnlyMode;
	BOOL _presented;
	BOOL _transitioning;
	BOOL _fullyRevealed;
	float _backgroundBrightness;
}
@property(readonly, assign, nonatomic) NSSet* tapExcludedViews;
@property(readonly, assign, nonatomic) NSSet* conflictingGestures;
@property(readonly, assign, nonatomic) NSSet* gestures;
@property(assign, nonatomic) id<SBPresentingDelegate> presentingDelegate;
@property(readonly, assign, nonatomic) unsigned hintEdge;
@property(readonly, assign, nonatomic) float hintDisplacement;
@property(readonly, assign, nonatomic) int coordinatedPresentingControllerIdentifier;
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(assign, nonatomic) float backgroundBrightness;
@property(assign, nonatomic, getter=isFullyRevealed) BOOL fullyRevealed;
@property(assign, nonatomic, getter=isTransitioning) BOOL transitioning;
@property(assign, nonatomic, getter=isPresented) BOOL presented;
@property(assign, nonatomic, getter=isUILocked) BOOL UILocked;
@property(assign, nonatomic) BOOL inGrabberOnlyMode;
+(void)notifyControlCenterControl:(id)control didActivate:(BOOL)activate;
+(id)sharedInstanceIfExists;
+(id)sharedInstance;
+(id)_sharedInstanceCreatingIfNeeded:(BOOL)needed;
-(void)controlCenterViewController:(id)controller backdropViewDidUpdate:(id)backdropView;
-(void)controlCenterViewController:(id)controller handlePan:(id)pan;
-(void)controlCenterViewController:(id)controller handleTap:(id)tap;
-(BOOL)controlCenterViewController:(id)controller canHandleGestureRecognizer:(id)recognizer;
-(void)controlCenterViewControllerWantsDismissal:(id)dismissal;
-(void)updateControlAlphaForBrightness:(float)brightness;
-(void)resetControlAlpha;
-(void)_finishPresenting:(BOOL)presenting completion:(id)completion;
-(void)_dismissWithDuration:(double)duration additionalAnimations:(id)animations completion:(id)completion;
-(void)dismissAnimated:(BOOL)animated withAdditionalAnimations:(id)additionalAnimations completion:(id)completion;
-(void)dismissAnimated:(BOOL)animated completion:(id)completion;
-(void)dismissAnimated:(BOOL)animated;
-(void)_presentWithDuration:(double)duration completion:(id)completion;
-(void)presentAnimated:(BOOL)animated;
-(void)presentAnimated:(BOOL)animated completion:(id)completion;
-(void)hideGrabberAnimated:(BOOL)animated completion:(id)completion;
-(void)hideGrabberAnimated:(BOOL)animated;
-(void)showGrabberAnimated:(BOOL)animated;
-(void)cancelTransition;
-(void)abortAnimatedTransition;
-(void)endTransitionWithVelocity:(CGPoint)velocity completion:(id)completion;
-(void)endTransitionWithVelocity:(CGPoint)velocity wasCancelled:(BOOL)cancelled completion:(id)completion;
-(float)_verticalPercentageMovedOnScreenForY:(float)y stopY:(float)y2;
-(void)_cleanupAnimator;
-(id)_newDynamicAnimationForShow:(BOOL)show currentValue:(double)value velocity:(double)velocity unitSize:(double)size;
-(void)updateTransitionWithTouchLocation:(CGPoint)touchLocation velocity:(CGPoint)velocity;
-(void)beginPresentationWithTouchLocation:(CGPoint)touchLocation;
-(void)beginTransitionWithTouchLocation:(CGPoint)touchLocation;
-(void)_clearCoveredContentSnapshot;
-(void)_updateCoveredContentSnapshot;
-(void)_endPresentation;
-(void)_beginPresentation;
-(BOOL)allowHideTransition;
-(BOOL)allowShowTransitionSystemGesture;
-(BOOL)_allowShowTransitionSystemGesture;
-(BOOL)allowShowTransition;
-(void)_setLockHUDHidden:(BOOL)hidden;
-(void)_updateGrabberVisibility;
-(void)_updateRevealPercentage:(float)percentage;
-(void)_revealSlidingViewToHeight:(float)height;
-(float)_controlCenterHeightForTouchLocation:(CGPoint)touchLocation;
-(float)_yValueForClosed;
-(float)_yValueForOpen;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(BOOL)shouldAutomaticallyForwardRotationMethods;
-(BOOL)shouldAutomaticallyForwardAppearanceMethods;
-(BOOL)wantsFullScreenLayout;
-(id)_window;
-(void)preventDismissalOnLock:(BOOL)lock forReason:(id)reason;
-(void)_dismissOnLock;
-(void)_uiRelockedNotification:(id)notification;
-(void)_lockStateChangedNotification:(id)notification;
-(BOOL)isGrabberVisible;
-(BOOL)isPresentingControllerTransitioning;
-(BOOL)isVisible;
-(void)loadView;
-(BOOL)handleMenuButtonTap;
-(void)removeObserver:(id)observer;
-(void)addObserver:(id)observer;
-(void)_enumerateObservers:(id)observers;
-(BOOL)isAvailableWhileLocked;
-(void)dealloc;
-(id)init;
@end

