/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class UIColor;

__attribute__((visibility("hidden")))
@interface SBControlColorSettings : XXUnknownSuperclass {
	UIColor* _tintColor;
	UIColor* _selectedTintColor;
	UIColor* _textColor;
	UIColor* _selectedTextColor;
}
@property(readonly, retain, nonatomic) UIColor* selectedTextColor;
@property(readonly, retain, nonatomic) UIColor* textColor;
@property(readonly, retain, nonatomic) UIColor* selectedTintColor;
@property(readonly, retain, nonatomic) UIColor* tintColor;
+(id)settingsWithTintColor:(id)tintColor selectedTintColor:(id)color textColor:(id)color3 selectedTextColor:(id)color4;
-(void)dealloc;
-(id)initWithTintColor:(id)tintColor selectedTintColor:(id)color textColor:(id)color3 selectedTextColor:(id)color4;
@end

