/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBFLockScreenDateFormatter.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, NSDateFormatter, NSNumberFormatter, NSDate;

__attribute__((visibility("hidden")))
@interface SBDateLabelStringFormatCache : XXUnknownSuperclass <SBFLockScreenDateFormatter> {
	NSDateFormatter* _dayOfWeekFormatter;
	NSDateFormatter* _dayOfWeekWithTimeFormatter;
	NSDateFormatter* _dayMonthYearFormatter;
	NSDateFormatter* _shortDayMonthFormatter;
	NSDateFormatter* _shortDayMonthTimeFormatter;
	NSDateFormatter* _abbrevDayMonthFormatter;
	NSDateFormatter* _abbrevDayMonthTimeFormatter;
	NSDateFormatter* _timeFormatter;
	NSDateFormatter* _relativeDateTimeFormatter;
	NSDateFormatter* _relativeDateFormatter;
	NSDateFormatter* _dayOfWeekMonthDayFormatter;
	NSDateFormatter* _timeNoAMPMFormatter;
	NSDateFormatter* _longYMDHMSZFormatter;
	NSDateFormatter* _longYMDHMSNoSpaceFormatter;
	NSNumberFormatter* _decimalFormatter;
	NSNumberFormatter* _timerNumberFormatter;
	NSDateFormatter* _abbreviatedTimerFormatter;
	NSDateFormatter* _alarmSnoozeFormatter;
	NSDate* _timerReferenceDate;
	NSDate* _alarmReferenceDate;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
+(id)sharedInstance;
+(void)load;
-(id)formatAlarmSnoozeDuration:(double)duration;
-(id)formatAbbreviatedTimerDuration:(double)duration;
-(id)formatTimerDuration:(double)duration;
-(id)formatDateAsRelativeDateStyle:(id)style;
-(BOOL)_shouldShowHoursForTimerDuration:(double)timerDuration;
-(id)formatDateAsLongYMDHMSNoSpacesWithDate:(id)date;
-(id)formatDateAsLongYMDHMSZWithDate:(id)date;
-(id)formatDateAsTimeNoAMPM:(id)ampm;
-(id)formatDateAsDayOfWeekMonthDayStyle:(id)weekMonthDayStyle;
-(id)formatDateAsRelativeDateAndTimeStyle:(id)style;
-(id)formatDateAsTimeStyle:(id)style;
-(id)formatDateAsAbbreviatedDayMonthWithTimeStyle:(id)timeStyle;
-(id)formatDateAsAbbreviatedDayMonthStyle:(id)style;
-(id)formatDateAsShortDayMonthWithTimeStyle:(id)timeStyle;
-(id)formatDateAsDayMonthYearStyle:(id)style;
-(id)formatDateAsAbbreviatedDayOfWeekWithTime:(id)time;
-(id)formatDateAsDayOfWeek:(id)week;
-(id)formatNumberAsDecimal:(id)decimal;
-(void)resetFormatters:(id)formatters;
-(void)resetFormattersIfNecessary;
-(void)_resetFormatters;
-(void)dealloc;
-(id)init;
@end

