/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBDeactivationSettings.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "NSObject.h"
#import "SpringBoard-Structs.h"
#import "NSCopying.h"
#import "BSSettingDescriptionProvider.h"

@class BSMutableSettings, NSString;

@protocol SBDeactivationSettings <NSObject>
-(void)applyDeactivationSettings:(id)settings;
-(id)objectForDeactivationSetting:(unsigned)deactivationSetting;
-(void)setObject:(id)object forDeactivationSetting:(unsigned)deactivationSetting;
-(BOOL)boolForDeactivationSetting:(unsigned)deactivationSetting;
-(int)flagForDeactivationSetting:(unsigned)deactivationSetting;
-(void)setFlag:(int)flag forDeactivationSetting:(unsigned)deactivationSetting;
@end

__attribute__((visibility("hidden")))
@interface SBDeactivationSettings : XXUnknownSuperclass <BSSettingDescriptionProvider, SBDeactivationSettings, NSCopying> {
	BSMutableSettings* _settings;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
-(id)valueDescriptionForFlag:(int)flag object:(id)object ofSetting:(unsigned)setting;
-(id)keyDescriptionForSetting:(unsigned)setting;
-(id)basicDescriptionWithPrefix:(id)prefix;
-(void)applyDeactivationSettings:(id)settings;
-(id)objectForDeactivationSetting:(unsigned)deactivationSetting;
-(void)setObject:(id)object forDeactivationSetting:(unsigned)deactivationSetting;
-(BOOL)boolForDeactivationSetting:(unsigned)deactivationSetting;
-(int)flagForDeactivationSetting:(unsigned)deactivationSetting;
-(void)setFlag:(int)flag forDeactivationSetting:(unsigned)deactivationSetting;
-(void)dealloc;
-(id)copyWithZone:(NSZone*)zone;
-(id)init;
@end

