/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "UIAlertViewDelegate.h"

@class NSObject, NSString, SBIcon;
@protocol OS_dispatch_semaphore;

__attribute__((visibility("hidden")))
@interface SBDeleteIconAlertItem : XXUnknownSuperclass <UIAlertViewDelegate> {
	SBIcon* _icon;
	BOOL _checkedDocumentsInCloudState;
	BOOL _appHasDocumentsInCloud;
	BOOL _appHasDocumentsWithPendingUpdates;
	BOOL _askedUserAboutDocumentsDocumentsInCloud;
	BOOL _askedUserAboutDocumentsWithPendingUpdates;
	BOOL _checkedForRelatedData;
	BOOL _finishedCheckingForRelatedData;
	BOOL _appHasHealthKitData;
	BOOL _appHasGameKitData;
	NSObject<OS_dispatch_semaphore>* _healthKitResponseSem;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
-(BOOL)_hasRelatedData;
-(void)_waitForRelatedDataResponsesIfNeeded;
-(void)_startCheckingForRelatedExternalDataIfNeeded;
-(BOOL)dismissOnLock;
-(BOOL)shouldShowInLockScreen;
-(void)configure:(BOOL)configure requirePasscodeForActions:(BOOL)actions;
-(void)_checkDocumentsInCloudStateIfNeeded;
-(void)alertView:(id)view clickedButtonAtIndex:(int)index;
-(id)icon;
-(void)dealloc;
-(id)initWithIcon:(id)icon;
@end

