/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "SBDateLabelDelegate.h"

@class NSString, UILabel, UIImage, NSAttributedString;
@protocol SBBulletinDateLabel;

__attribute__((visibility("hidden")))
@interface SBDefaultBannerTextView : XXUnknownSuperclass <SBDateLabelDelegate> {
	NSAttributedString* _primaryTextAttributedString;
	NSAttributedString* _primaryTextAttributedStringComponent;
	UIImage* _primaryTextAccessoryImageComponent;
	NSAttributedString* _secondaryTextAttributedString;
	NSAttributedString* _alternateSecondaryTextAttributedString;
	UILabel<SBBulletinDateLabel>* _relevanceDateLabel;
	float _secondaryTextAlpha;
	float _alternateSecondaryTextAlpha;
}
@property(readonly, assign, nonatomic) UILabel* relevanceDateLabel;
@property(copy, nonatomic) NSString* alternateSecondaryText;
@property(copy, nonatomic) NSString* secondaryText;
@property(retain, nonatomic) UIImage* primaryTextAccessoryImage;
@property(copy, nonatomic) NSString* primaryText;
+(id)_defaultRelevanceDateFont;
+(id)_secondaryItalicTextFont;
+(id)_secondaryTextFont;
+(id)_primaryTextFont;
-(void)drawRect:(CGRect)rect;
-(void)layoutSubviews;
-(CGSize)sizeThatFits:(CGSize)fits;
-(BOOL)_hasSecondaryText;
-(CGSize)_primaryTextSizeForBounds:(CGRect)bounds;
-(CGRect)_maximumSecondaryTextRectForBounds:(CGRect)bounds;
-(CGRect)_secondaryTextRectForBounds:(CGRect)bounds attributedString:(id)string;
-(CGRect)_primaryTextRectForBounds:(CGRect)bounds;
-(float)_secondaryTextOriginYForBounds:(CGRect)bounds;
-(float)_primaryTextBaselineForBounds:(CGRect)bounds;
-(id)_primaryTextAttributedString;
-(void)_invalidatePrimaryTextAttributedString;
-(BOOL)_isItalicizedAttributedString:(id)string;
-(id)_newAttributedStringForSecondaryText:(id)secondaryText italicized:(BOOL)italicized;
-(void)_setSecondaryText:(id)text italicized:(BOOL)italicized forAttributedStringPtr:(id*)attributedStringPtr;
-(void)setAlternateSecondaryTextAlpha:(float)alpha;
-(void)setSecondaryTextAlpha:(float)alpha;
-(void)dateLabelDidChange:(id)dateLabel;
-(BOOL)textWillWrapForWidth:(float)text;
-(void)setRelevanceDate:(id)date;
-(void)setAlternateSecondaryText:(id)text italicized:(BOOL)italicized;
-(void)setSecondaryText:(id)text italicized:(BOOL)italicized;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
@end

