/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class SBDisplayLayout;

__attribute__((visibility("hidden")))
@interface SBDisplayLayoutManager : XXUnknownSuperclass {
	SBDisplayLayout* _activeLayout;
}
@property(retain, nonatomic) SBDisplayLayout* activeLayout;
+(id)sharedInstance;
-(id)init;
@end

