/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "SpringBoard-Structs.h"
#import "NSCopying.h"

@class NSString, NSMutableArray, NSArray;

__attribute__((visibility("hidden")))
@interface SBDisplayLayout : XXUnknownSuperclass <NSCopying> {
	int _layoutSize;
	NSMutableArray* _displayItems;
	NSString* _uniqueStringRepresentation;
}
@property(readonly, assign, nonatomic) NSArray* displayItems;
@property(readonly, assign, nonatomic) int layoutSize;
+(id)fullScreenDisplayLayoutForApplication:(id)application;
+(id)homeScreenDisplayLayout;
+(id)displayLayoutWithPlistRepresentation:(id)plistRepresentation;
+(id)displayLayoutWithLayoutSize:(int)layoutSize displayItems:(id)items;
-(id)displayLayoutBySettingSize:(int)size;
-(id)displayLayoutByReplacingDisplayItemOnSide:(int)side withDisplayItem:(id)displayItem;
-(id)displayLayoutByRemovingDisplayItems:(id)items;
-(id)displayLayoutByRemovingDisplayItem:(id)item;
-(id)displayLayoutByAddingDisplayItem:(id)item side:(int)side withLayout:(int)layout;
-(BOOL)isEqual:(id)equal;
-(unsigned)hash;
-(id)uniqueStringRepresentation;
-(id)_calculateUniqueStringRepresentation;
-(id)description;
-(id)copyWithZone:(NSZone*)zone;
-(void)dealloc;
-(id)plistRepresentation;
-(id)initWithLayoutSize:(int)layoutSize displayItems:(id)items;
@end

