/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "SpringBoard-Structs.h"
#import "NSCopying.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface SBDisplayItem : XXUnknownSuperclass <NSCopying> {
	NSString* _uniqueStringRepresentation;
	NSString* _type;
	NSString* _displayIdentifier;
}
@property(readonly, assign, nonatomic) NSString* displayIdentifier;
@property(readonly, assign, nonatomic) NSString* type;
+(id)displayItemWithType:(NSString*)type displayIdentifier:(id)identifier;
-(BOOL)isEqual:(id)equal;
-(unsigned)hash;
-(id)uniqueStringRepresentation;
-(id)_calculateUniqueStringRepresentation;
-(id)description;
-(void)dealloc;
-(id)copyWithZone:(NSZone*)zone;
-(id)plistRepresentation;
-(id)initWithPlistRepresentation:(id)plistRepresentation;
-(id)initWithType:(NSString*)type displayIdentifier:(id)identifier;
@end

