/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBActivationSettings.h"
#import "SBDeactivationSettings.h"
#import "SBStateSettings.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class SBDeactivationSettings, NSString, SBStateSettings, SBActivationSettings;

__attribute__((visibility("hidden")))
@interface SBDisplaySettings : XXUnknownSuperclass <SBActivationSettings, SBDeactivationSettings, SBStateSettings> {
	SBActivationSettings* _activationSettings;
	SBDeactivationSettings* _deactivationSettings;
	SBStateSettings* _stateSettings;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(retain, nonatomic) SBDeactivationSettings* deactivationSettings;
@property(retain, nonatomic) SBActivationSettings* activationSettings;
@property(retain, nonatomic) SBStateSettings* stateSettings;
-(void)applyStateSettings:(id)settings;
-(id)objectForStateSetting:(unsigned)stateSetting;
-(void)setObject:(id)object forStateSetting:(unsigned)stateSetting;
-(BOOL)boolForStateSetting:(unsigned)stateSetting;
-(int)flagForStateSetting:(unsigned)stateSetting;
-(void)setFlag:(int)flag forStateSetting:(unsigned)stateSetting;
-(void)applyDeactivationSettings:(id)settings;
-(id)objectForDeactivationSetting:(unsigned)deactivationSetting;
-(void)setObject:(id)object forDeactivationSetting:(unsigned)deactivationSetting;
-(BOOL)boolForDeactivationSetting:(unsigned)deactivationSetting;
-(int)flagForDeactivationSetting:(unsigned)deactivationSetting;
-(void)setFlag:(int)flag forDeactivationSetting:(unsigned)deactivationSetting;
-(void)applyActivationSettings:(id)settings;
-(id)objectForActivationSetting:(unsigned)activationSetting;
-(void)setObject:(id)object forActivationSetting:(unsigned)activationSetting;
-(BOOL)boolForActivationSetting:(unsigned)activationSetting;
-(int)flagForActivationSetting:(unsigned)activationSetting;
-(void)setFlag:(int)flag forActivationSetting:(unsigned)activationSetting;
-(void)dealloc;
-(id)init;
@end

