/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBRootIconListView.h"


__attribute__((visibility("hidden")))
@interface SBDockIconListView : SBRootIconListView {
}
+(unsigned)iconRowsForInterfaceOrientation:(int)interfaceOrientation;
+(unsigned)iconColumnsForInterfaceOrientation:(int)interfaceOrientation;
+(unsigned)iconColumnsOrRows;
+(float)defaultHeight;
-(unsigned)columnAtPoint:(CGPoint)point;
-(CGPoint)originForIconAtCoordinate:(SBIconCoordinate)coordinate;
-(float)_additionalVerticalInsetToCenterIcons;
-(float)_additionalHorizontalInsetToCenterIcons;
-(unsigned)rowAtPoint:(CGPoint)point;
-(id)iconAtPoint:(CGPoint)point index:(unsigned*)index proposedOrder:(int*)order grabbedIcon:(id)icon;
-(float)sideIconInset;
-(float)bottomIconInset;
-(float)topIconInset;
-(unsigned)iconsInColumnForSpacingCalculation;
-(unsigned)iconsInRowForSpacingCalculation;
-(BOOL)_shouldAnimatePropertyWithKey:(id)key;
-(int)iconLocation;
-(id)initWithModel:(id)model orientation:(int)orientation viewMap:(id)map;
@end

