/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class UIView;

__attribute__((visibility("hidden")))
@interface SBDosidoAnimator : XXUnknownSuperclass {
	int _fromOrientation;
	UIView* _parentView;
	UIView* _transformContainer;
	UIView* _transformedContent;
	UIView* _fromView;
	UIView* _toView;
}
@property(retain, nonatomic, getter=_toView, setter=_setToView:) UIView* toView;
@property(retain, nonatomic, getter=_fromView, setter=_setFromView:) UIView* fromView;
@property(readonly, assign, nonatomic) float defaultDuration;
@property(readonly, assign, nonatomic) UIView* animationContainerView;
-(void)_rotateViewIfNecessary:(id)necessary inverted:(BOOL)inverted;
-(void)_doReducedMotionDosido:(id)dosido completion:(id)completion;
-(void)_doRealDosido:(id)dosido withSpacingBetween:(float)spacingBetween completion:(id)completion;
-(id)_transformedContentView;
-(void)animateFromView:(id)view toView:(id)view2 withSpacingBetween:(float)spacingBetween outAnimationFactory:(id*)factory completion:(id)completion;
-(void)dealloc;
-(id)initWithParentView:(id)parentView fromOrientation:(int)orientation;
@end

