/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface SBFAnimationFactorySettings : XXUnknownSuperclass {
	BOOL _isArchiveValue;
	BOOL _slowAnimations;
	float _slowDownFactor;
	float _springMassFactor;
	float _springStiffnessFactor;
	float _springDampingFactor;
}
@property(assign, nonatomic) float springDampingFactor;
@property(assign, nonatomic) float springStiffnessFactor;
@property(assign, nonatomic) float springMassFactor;
@property(assign, nonatomic) float slowDownFactor;
@property(assign, nonatomic) BOOL slowAnimations;
+(id)settingsControllerModule;
-(void)applyArchiveValue:(id)value forKey:(id)key;
-(void)setValue:(id)value forKey:(id)key;
-(id)valueForKey:(id)key;
-(void)setDefaultValues;
@end

