/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBFolderView.h"
#import "SpringBoard-Structs.h"
#import "UIGestureRecognizerDelegate.h"
#import "_UISettingsKeyObserver.h"

@class SBFolderSettings, NSMapTable, SBFloatyFolderBackgroundClipView, UIPinchGestureRecognizer, NSString, UITapGestureRecognizer, UILongPressGestureRecognizer, NSMutableArray;

__attribute__((visibility("hidden")))
@interface SBFloatyFolderView : SBFolderView <UIGestureRecognizerDelegate, _UISettingsKeyObserver> {
	SBFloatyFolderBackgroundClipView* _scrollClipView;
	NSMutableArray* _pageBackgroundViews;
	NSMapTable* _pageBackgroundViewsForIconListViews;
	unsigned _scalingViewPageIndex;
	UITapGestureRecognizer* _tapGesture;
	UIPinchGestureRecognizer* _pinchGesture;
	UILongPressGestureRecognizer* _longPressGesture;
	SBFolderSettings* _folderSettings;
	CGPoint _preReachabilityTitleOrigin;
	CGPoint _reachabilityTitleOrigin;
	CGPoint _preReachabilityScaleOrigin;
	CGPoint _reachabilityScaleOrigin;
	float _reachabilityYOffset;
	BOOL _layingOutForReachability;
	BOOL _displayingMultipleIconLists;
	BOOL _animatingRotation;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(assign, nonatomic, getter=isAnimatingRotation) BOOL animatingRotation;
@property(assign, nonatomic, getter=isDisplayingMultipleIconLists) BOOL displayingMultipleIconLists;
+(unsigned)_countOfAdditionalPagesToKeepVisibleInOneDirection;
+(Class)_scrollViewClass;
-(void)_handleReachabilityDectivatedAnimate:(BOOL)animate completion:(id)completion;
-(void)_handleReachabilityActivatedAnimate:(BOOL)animate completion:(id)completion;
-(float)reachabilityYOffset;
-(void)handleReachabilityActivated:(BOOL)activated animated:(BOOL)animated completion:(id)completion;
-(void)settings:(id)settings changedValueForKey:(id)key;
-(BOOL)gestureRecognizer:(id)recognizer shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)gestureRecognizer;
-(BOOL)gestureRecognizer:(id)recognizer shouldReceiveTouch:(id)touch;
-(BOOL)_tapToCloseGestureRecognizer:(id)closeGestureRecognizer shouldReceiveTouch:(id)touch;
-(void)_handleLongPressGesture:(id)gesture;
-(void)_handlePinchGesture:(id)gesture;
-(void)_handleOutsideTap:(id)tap;
-(void)_configureGestures;
-(void)_convertToSingleIconListAnimated:(BOOL)singleIconListAnimated;
-(void)_convertToMultipleIconListsAnimated:(BOOL)multipleIconListsAnimated;
-(void)fadeContentForMinificationFraction:(float)minificationFraction;
-(void)fadeContentForMagnificationFraction:(float)magnificationFraction;
-(void)returnScalingView;
-(id)borrowScalingView;
-(void)didAnimate;
-(void)willAnimate;
-(float)_titleVerticalOffsetForOrientation:(int)orientation;
-(float)_titleFontSize;
-(BOOL)_showsTitle;
-(id)iconListViewAtPoint:(CGPoint)point;
-(BOOL)locationCountsAsInsideFolder:(CGPoint)folder;
-(float)_offsetToCenterPageControlInSpaceForPageControl;
-(CGRect)_frameForScalingView;
-(void)_updateScalingViewLocation;
-(void)_currentPageIndexDidChange;
-(void)_updateIconListContainment:(id)containment atIndex:(unsigned)index;
-(CGRect)_iconListFrameForPageRect:(CGRect)pageRect atIndex:(unsigned)index;
-(CGRect)_pageBackgroundFrameForPageRect:(CGRect)pageRect;
-(void)_layoutSubviews;
-(void)didRotateFromInterfaceOrientation:(int)interfaceOrientation;
-(void)willAnimateRotationToInterfaceOrientation:(int)interfaceOrientation duration:(double)duration;
-(void)_orientationDidChange:(int)_orientation;
-(BOOL)_shouldConvertToMultipleIconListsInLandscapeOrientation;
-(unsigned)_countOfAdditionalPagesToKeepAnimatingInOneDirection;
-(void)_removeIconListView:(id)view;
-(void)_addIconListView:(id)view;
-(id)_newPageBackgroundView;
-(void)setLegibilitySettings:(id)settings;
-(CGPoint)visibleFolderRelativeImageCenterForIcon:(id)icon;
-(void)setBackgroundAlpha:(float)alpha;
-(void)dealloc;
-(id)initWithFolder:(id)folder orientation:(int)orientation viewMap:(id)map;
@end

