/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBScaleIconZoomAnimator.h"

@class SBFolderZoomSettings, SBFolderIconView, SBFolderIcon, _SBInnerFolderIconZoomAnimator, SBFloatyFolderView, SBFolderController;

__attribute__((visibility("hidden")))
@interface SBFolderIconZoomAnimator : SBScaleIconZoomAnimator {
	SBFolderController* _innerFolderController;
	SBFloatyFolderView* _innerFolderView;
	_SBInnerFolderIconZoomAnimator* _innerZoomAnimator;
}
@property(readonly, retain, nonatomic) SBFolderIconView* targetIconView;
@property(readonly, retain, nonatomic) SBFolderIcon* targetIcon;
@property(retain, nonatomic) SBFolderZoomSettings* settings;
-(BOOL)_forceSquareZoomDimension;
-(CGRect)_zoomedFrame;
-(void)_animateToFraction:(float)fraction afterDelay:(double)delay withSharedCompletion:(id)sharedCompletion;
-(unsigned)_numberOfSignificantAnimations;
-(void)_cleanupAnimation;
-(void)_setAnimationFraction:(float)fraction;
-(void)_prepareAnimation;
-(void)dealloc;
-(id)initWithOuterController:(id)outerController innerController:(id)controller folderIcon:(id)icon;
@end

