/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class _UISettingsGroup;

__attribute__((visibility("hidden")))
@interface SBHomeButtonSettings : XXUnknownSuperclass {
	BOOL _doubleTapOnMenuDown;
	BOOL _useDynamicTapTiming;
	_UISettingsGroup* _tapTimingGroup;
}
@property(retain) _UISettingsGroup* tapTimingGroup;
@property(assign, nonatomic) BOOL useDynamicTapTiming;
@property(assign, nonatomic) BOOL doubleTapOnMenuDown;
+(id)settingsControllerModule;
-(void)setDefaultValues;
@end

