/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBReusableViewMap.h"


__attribute__((visibility("hidden")))
@interface SBIconAccessoryViewMap : SBReusableViewMap {
}
+(id)homescreenMap;
-(void)recycleView:(id)view;
-(id)viewOfClass:(Class)aClass;
@end

