/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class SBIconPageIndicatorImageSetResult, _UILegibilitySettings;

__attribute__((visibility("hidden")))
@interface SBIconPageIndicatorImageSetCache : XXUnknownSuperclass {
	_UILegibilitySettings* _legibilitySettings;
	SBIconPageIndicatorImageSetResult* _indicatorImageSetResults;
}
+(id)homescreenPageIndicatorImageSetCache;
-(id)_emptyPageIndicatorSet;
-(id)pageIndicatorImageSetForLegibilitySettings:(id)legibilitySettings;
-(void)setLegibilitySettings:(id)settings;
-(void)dealloc;
@end

