/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "SBCountedMapValue.h"

@class NSString, SBIconLabelImageParameters;

__attribute__((visibility("hidden")))
@interface SBIconLabelImage : XXUnknownSuperclass <SBCountedMapValue> {
	SBIconLabelImageParameters* _parameters;
	CGPoint _maxSizeOffset;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(readonly, assign, nonatomic) CGPoint maxSizeOffset;
@property(readonly, copy, nonatomic) SBIconLabelImageParameters* parameters;
+(void)checkinLabelImage:(id)image;
+(id)_parametersWithDefaultStyle:(id)defaultStyle;
+(id)checkoutLabelImageForParameters:(id)parameters;
+(id)_drawLabelImageForParameters:(id)parameters;
+(id)_labelImageCountedMap;
+(void)drawImageInRect:(CGRect)rect fromParameters:(id)parameters;
+(CGRect)rectFromParameters:(id)parameters constrainedToRect:(CGRect)rect;
+(void)applyKerning:(float)kerning whitespaceKerning:(float)kerning2 toAttributedString:(id)attributedString;
+(CGRect)_rectWithDrawing:(BOOL)drawing inRect:(CGRect)rect fromParameters:(id)parameters;
-(id)countedMapKey;
-(void)dealloc;
-(id)initWithCGImage:(CGImageRef)cgimage scale:(float)scale orientation:(int)orientation;
-(id)_initWithCGImage:(CGImageRef)cgimage scale:(float)scale orientation:(int)orientation parameters:(id)parameters maxSizeOffset:(CGPoint)offset;
@end

