/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class _UILegibilityImageSet;

__attribute__((visibility("hidden")))
@interface SBIconPageIndicatorImageSetResult : XXUnknownSuperclass {
	_UILegibilityImageSet* _pageIndicatorSet;
	_UILegibilityImageSet* _enabledPageIndicatorSet;
}
@property(readonly, assign, nonatomic) _UILegibilityImageSet* enabledPageIndicatorSet;
@property(readonly, assign, nonatomic) _UILegibilityImageSet* pageIndicatorSet;
-(void)dealloc;
-(id)initWithIndicatorSet:(id)indicatorSet enabledIndicatorSet:(id)set;
@end

