/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBLockScreenActionHandler.h"


@protocol SBLockScreenNotificationViewDelegate <SBLockScreenActionHandler>
-(void)noteListViewReadyForModelUpdate;
-(void)listView:(id)view cellDidEndScrolling:(id)cell;
-(void)listView:(id)view cellDidBeginScrolling:(id)cell;
-(void)listViewDidEndScrolling:(id)listView;
-(void)listViewDidBeginScrolling:(id)listView;
-(id)lockScreenScrollView;
-(void)noteUnlockActionChanged:(id)changed;
@end

