/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class SBUIBiometricEventMonitor, NSMutableArray, NSArray, SBAlertItem;

__attribute__((visibility("hidden")))
@interface SBLockScreenModalAlertViewController : XXUnknownSuperclass {
	NSMutableArray* _pendingAlertItems;
	NSMutableArray* _pendingSuperModalAlertItems;
	NSMutableArray* _presentedAlertItems;
	SBAlertItem* _currentAlertItem;
	SBUIBiometricEventMonitor* _bioEventMonitor;
}
@property(readonly, assign, nonatomic) NSArray* presentedAlertItems;
@property(readonly, assign, nonatomic) SBAlertItem* currentAlertItem;
-(void)_pendOrDeactivateAlertItem:(id)item animated:(BOOL)animated;
-(void)_removePresentedAlertItem:(id)item;
-(void)_addPresentedAlertItem:(id)item;
-(void)_pendAlertItem:(id)item;
-(id)allPendingAlertItems;
-(BOOL)hasSuperModalAlertItems;
-(id)dequeueAllPendingSuperModalAlertItems;
-(void)pendOrDeactivateCurrentAlertItem;
-(id)dequeueAllPendingAlertItems;
-(void)deactivateAlertItem:(id)item animated:(BOOL)animated;
-(BOOL)activateAlertItem:(id)item pended:(BOOL)pended animated:(BOOL)animated;
-(void)dealloc;
-(id)initWithNibName:(id)nibName bundle:(id)bundle;
@end

