/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */



@protocol SBLockScreenSlideUpToAppControllerDelegate
-(id)viewControllerToUseAsParent;
-(void)passcodeViewDidBecomeActive:(BOOL)passcodeView forController:(id)controller;
-(void)updateSlideToUnlockTextForController:(id)controller;
-(void)setUnlockActionContext:(id)context;
-(BOOL)isAnotherSlideUpControllerBlockingController:(id)controller;
-(BOOL)controllerShouldInvertVerticalPadding:(id)controller;
-(BOOL)controllerShouldUseAdditionalTopPadding:(id)controller;
-(void)adjustWallpaperForVerticalScrollPercentage:(float)verticalScrollPercentage;
-(id)grabberViewInLockScreenView:(id)lockScreenView forController:(id)controller;
-(void)addGrabberView:(id)view toLockScreenView:(id)lockScreenView forController:(id)controller;
-(int)presentingControllerIdentifierForController:(id)controller;
-(void)prepareForSlideUpAppLaunchAnimated:(BOOL)slideUpAppLaunchAnimated;
@end

