/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBLockScreenBuddyViewDelegate.h"
#import "SpringBoard-Structs.h"
#import "SBLockOverlayViewController.h"

@class NSArray, NSDictionary, NSTimer, NSString, SBActivationInfoViewController, SBLockScreenViewController, NSMutableArray;

__attribute__((visibility("hidden")))
@interface SBLockScreenBuddyViewController : SBLockOverlayViewController <SBLockScreenBuddyViewDelegate> {
	NSMutableArray* _currentStringsOrdering;
	BOOL _needsTransitionFromFakeLogoToWelcomeStrings;
	BOOL _cyclingLabels;
	BOOL _viewVisible;
	WiFiManagerClient* _wifiManager;
	WiFiDeviceClient* _wifiDevice;
	BOOL _showingBootLogo;
	BOOL _startsWithBlackBackground;
	BOOL _hasResultsFromWifiScan;
	BOOL _shouldResetOrderingOnNextCycle;
	SBLockScreenViewController* _lockScreenViewController;
	NSDictionary* _localizedStrings;
	NSArray* _stringsOrdering;
	unsigned _currentStringIndex;
	NSTimer* _stringCycleTimer;
	SBActivationInfoViewController* _activationInfoViewController;
	NSString* _telephonyPrimaryLanguage;
	NSString* _wifiPrimaryLanguage;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(assign, nonatomic) BOOL shouldResetOrderingOnNextCycle;
@property(assign, nonatomic) BOOL hasResultsFromWifiScan;
@property(assign, nonatomic) BOOL startsWithBlackBackground;
@property(assign, nonatomic, getter=isShowingBootLogo) BOOL showingBootLogo;
@property(retain, nonatomic) SBActivationInfoViewController* activationInfoViewController;
@property(retain, nonatomic) NSTimer* stringCycleTimer;
@property(copy, nonatomic) NSString* telephonyPrimaryLanguage;
@property(copy, nonatomic) NSString* wifiPrimaryLanguage;
@property(assign, nonatomic) unsigned currentStringIndex;
@property(copy, nonatomic) NSArray* stringsOrdering;
@property(copy, nonatomic) NSDictionary* localizedStrings;
@property(assign, nonatomic) SBLockScreenViewController* lockScreenViewController;
@property(readonly, assign, nonatomic) NSString* slideToUnlockText;
-(void)handleTapGestureFromView:(id)view;
-(void)buddyView:(id)view didChangeToStyle:(unsigned)style;
-(void)_closeWifiConnection;
-(void)_wifiScanComplete:(CFArrayRef)complete error:(BOOL)error;
-(void)_startWifiScan;
-(void)_didHideBootSetupLogo:(id)logo;
-(void)_didShowBootSetupLogo:(id)logo;
-(void)_toggleShowsIMEIandICCID:(id)iccid;
-(void)_cycleTimerDidFire:(id)_cycleTimer;
-(void)_updateDisplayedStrings;
-(void)_resetDisplayedLocalizedStringsImmediately:(BOOL)immediately;
-(void)_startCyclingLocalizedStringsWithDelay:(double)delay;
-(void)_startCyclingLocalizedStrings;
-(void)_updateWifiPrimaryLanguageFromGuessedCountries:(id)guessedCountries;
-(void)_fetchLanguageFromTelephony;
-(id)_importantLanguageIdentifiers;
-(id)_currentLanguageIdentifier;
-(id)_currentStringsDictionary;
-(void)_transitionFromFakeBootLogoToWelcomeStrings;
-(void)_noteLogoVisible:(BOOL)visible;
-(void)_removeAllHiddenReasons;
-(void)viewDidDisappear:(BOOL)view;
-(void)viewWillDisappear:(BOOL)view;
-(void)viewDidAppear:(BOOL)view;
-(void)viewWillAppear:(BOOL)view;
-(id)buddyView;
-(void)loadView;
-(void)stopCyclingLocalizedStrings;
-(void)setInScreenOffMode:(BOOL)screenOffMode;
-(void)dealloc;
-(id)initWithLockScreenViewController:(id)lockScreenViewController;
@end

