/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class BBBulletin, NSString;

__attribute__((visibility("hidden")))
@interface SBLockScreenActionContext : XXUnknownSuperclass {
	NSString* _lockLabel;
	NSString* _shortLockLabel;
	id _action;
	NSString* _identifier;
	float _fontSize;
	BOOL _requiresUIUnlock;
	BOOL _deactivateAwayController;
	BOOL _canBypassPinLock;
	BOOL _requiresAuthentication;
	BBBulletin* _bulletin;
}
@property(assign, nonatomic) BBBulletin* bulletin;
@property(assign, nonatomic) BOOL requiresAuthentication;
@property(readonly, assign, nonatomic) BOOL hasCustomUnlockLabel;
@property(assign, nonatomic) BOOL canBypassPinLock;
@property(assign, nonatomic) BOOL deactivateAwayController;
@property(assign, nonatomic) BOOL requiresUIUnlock;
@property(copy, nonatomic) id action;
@property(retain, nonatomic) NSString* shortLockLabel;
@property(retain, nonatomic) NSString* lockLabel;
@property(retain, nonatomic) NSString* identifier;
-(void)dealloc;
-(id)initWithLockLabel:(id)lockLabel shortLockLabel:(id)label action:(id)action identifier:(id)identifier;
@end

