/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBUIPasscodeLockViewDelegate.h"
#import "SBLockOverlayViewController.h"

@class NSString, SBUIPasscodeViewWithLockScreenStyle;

__attribute__((visibility("hidden")))
@interface SBLockScreenPasscodeOverlayViewController : SBLockOverlayViewController <SBUIPasscodeLockViewDelegate> {
	SBUIPasscodeViewWithLockScreenStyle* _passcodeView;
	BOOL _attemptingUnlock;
	id _completionBlock;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(copy, nonatomic) id completionBlock;
-(void)_passcodeLockViewPasscodeEntered:(id)entered viaMesa:(BOOL)mesa;
-(void)passcodeLockViewCancelButtonPressed:(id)pressed;
-(void)passcodeLockViewPasscodeEnteredViaMesa:(id)mesa;
-(void)passcodeLockViewPasscodeEntered:(id)entered;
-(void)passcodeLockViewPasscodeDidChange:(id)passcodeLockViewPasscode;
-(id)_newPasscodeView;
-(void)viewWillAppear:(BOOL)view;
-(void)dealloc;
-(void)loadView;
@end

