/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface SBLockScreenActionContextFactory : XXUnknownSuperclass {
}
+(id)sharedInstance;
-(id)lockScreenActionContextForActivityBlock:(id)activityBlock;
-(id)lockScreenActionContextForContinuityApp:(id)continuityApp withUniqueIdentifier:(id)uniqueIdentifier andActivityTypeIdentifier:(id)identifier appSuggestion:(id)suggestion;
-(id)lockScreenActionContextForWidgetRequest:(id)widgetRequest;
-(id)lockScreenActionContextForSnoozedAlarmItem:(id)snoozedAlarmItem;
-(id)lockScreenActionContextForCardItem:(id)cardItem;
-(id)lockScreenActionContextForAlertItem:(id)alertItem;
-(id)lockScreenActionContextForBulletin:(id)bulletin action:(id)action origin:(int)origin pluginActionsAllowed:(BOOL)allowed context:(id)context completion:(id)completion;
-(id)lockScreenActionContextForBulletin:(id)bulletin withOrigin:(int)origin pluginActionsAllowed:(BOOL)allowed;
@end

