/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface SBMaskEndGradientView : XXUnknownSuperclass {
	BOOL _rightward;
}
+(Class)layerClass;
+(float)naturalWidth;
-(BOOL)isRightward;
-(id)selfLayer;
-(void)setFrame:(CGRect)frame;
-(id)initWithFrame:(CGRect)frame rightward:(BOOL)rightward;
@end

