/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSURL, NSArray;

__attribute__((visibility("hidden")))
@interface SBManyApplicationsAlertItem : XXUnknownSuperclass {
	NSURL* _url;
	NSArray* _applications;
	id _completion;
}
@property(readonly, copy, nonatomic) id completion;
@property(readonly, retain, nonatomic) NSArray* applications;
@property(readonly, copy, nonatomic) NSURL* url;
-(void)alertView:(id)view clickedButtonAtIndex:(int)index;
-(BOOL)allowMenuButtonDismissal;
-(BOOL)dismissOnLock;
-(BOOL)shouldShowInLockScreen;
-(void)configure:(BOOL)configure requirePasscodeForActions:(BOOL)actions;
-(void)dealloc;
-(id)initWithURL:(id)url applications:(id)applications completion:(id)completion;
-(id)init;
@end

