/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class SBMaskEndGradientView;

__attribute__((visibility("hidden")))
@interface SBMaskEndGradientClippingView : XXUnknownSuperclass {
	SBMaskEndGradientView* _gradientView;
}
-(BOOL)isRightward;
-(void)layoutSubviews;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame rightward:(BOOL)rightward;
@end

