/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableDictionary, CMGestureManager;

__attribute__((visibility("hidden")))
@interface SBMotionGestureController : XXUnknownSuperclass {
	NSMutableDictionary* _observersByPriority;
	CMGestureManager* _motionGestureManager;
}
+(id)sharedInstance;
+(void)initialize;
-(void)_removeGestureManager;
-(void)_addGestureManager;
-(void)_updateGestureManager;
-(id)_observersForPriority:(unsigned)priority;
-(id)_highestPriorityObservers;
-(void)_enumerateObserversByPriority:(id)priority;
-(BOOL)_hasObservers;
-(void)_notifyObserversOfGesture:(int)gesture;
-(void)_removeGestureObserver:(id)observer;
-(void)_addGestureObserver:(id)observer withPriority:(unsigned)priority;
-(void)removeGestureObserver:(id)observer;
-(void)addGestureObserver:(id)observer withPriority:(unsigned)priority;
-(void)addGestureObserver:(id)observer;
-(void)dealloc;
-(id)init;
@end

