/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableArray, NSArray;

__attribute__((visibility("hidden")))
@interface SBModeControlManager : XXUnknownSuperclass {
	NSMutableArray* _views;
}
@property(assign, nonatomic) int selectedSegmentIndex;
@property(readonly, assign, nonatomic) unsigned numberOfSegments;
@property(readonly, assign, nonatomic) NSArray* views;
+(id)_segmentedControlForUse:(int)use colorSettings:(id)settings;
+(void)_configureSegmentedControl:(id)control withColorSettings:(id)colorSettings;
-(void)setTintColor:(id)color forUse:(int)use;
-(void)removeAllSegments;
-(void)insertSegmentWithTitle:(id)title atIndex:(unsigned)index animated:(BOOL)animated;
-(void)addTarget:(id)target action:(SEL)action;
-(id)_segmentedControlForUse:(int)use;
-(void)setFrame:(CGRect)frame;
-(void)dealloc;
-(id)initWithGraphicsQuality:(int)graphicsQuality;
@end

