/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "SpringBoard-Structs.h"
#import "_UISettingsKeyPathObserver.h"
#import "SBUISizeObservingViewDelegate.h"

@class SBBulletinObserverViewController, NSString, UIView, UIScrollView, NSArray, SBNotificationSeparatorView, UISwipeGestureRecognizer, SBModeControlManager, UIViewController;
@protocol SBBulletinActionHandler, SBModeViewControllerContentProviding;

__attribute__((visibility("hidden")))
@interface SBModeViewController : XXUnknownSuperclass <SBUISizeObservingViewDelegate, _UISettingsKeyPathObserver> {
	id<SBBulletinActionHandler> _delegate;
	SBBulletinObserverViewController* _selectedViewController;
	SBBulletinObserverViewController* _deselectedViewController;
	UIScrollView* _contentView;
	UIView* _headerView;
	SBModeControlManager* _modeControl;
	UISwipeGestureRecognizer* _leftSwipeGestureRecognizer;
	UISwipeGestureRecognizer* _rightSwipeGestureRecognizer;
	SBNotificationSeparatorView* _separator;
	struct {
		unsigned isContentLayoutValid : 1;
		unsigned isSegmentLayoutValid : 1;
		unsigned isRequestHandlingEnabled : 1;
		unsigned shouldLoadAllChildViews : 1;
	} _modeViewControllerFlags;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(retain, nonatomic) SBBulletinObserverViewController* deselectedViewController;
@property(assign, nonatomic, getter=isRequestHandlingEnabled) BOOL requestHandlingEnabled;
@property(retain, nonatomic) NSArray* viewControllers;
@property(assign, nonatomic) UIViewController<SBModeViewControllerContentProviding>* selectedViewController;
@property(assign, nonatomic) id<SBBulletinActionHandler> delegate;
+(id)_buttonTitleFont;
-(void)settings:(id)settings changedValueForKeyPath:(id)keyPath;
-(void)hostDidDismiss;
-(void)hostWillDismiss;
-(void)hostDidPresent;
-(void)hostWillPresent;
-(void)setWidgetDelegate:(id)delegate;
-(id)widgetDelegate;
-(BOOL)handleAction:(id)action forBulletin:(id)bulletin withCompletion:(id)completion;
-(CGRect)rectForBulletin:(id)bulletin;
-(BOOL)_isRequestHandlingEnabled;
-(void)handleModeChange:(id)change;
-(void)setSelectedViewController:(id)controller animated:(BOOL)animated;
-(void)_setSelectedBulletinObserverViewController:(id)controller animated:(BOOL)animated;
-(BOOL)_contentOffset:(CGPoint*)offset forChildViewController:(id)childViewController;
-(void)removeViewController:(id)controller;
-(void)addViewController:(id)controller;
-(BOOL)_addBulletinObserverViewController:(id)controller;
-(void)_setSelectedSegmentIndex:(int)index;
-(void)sizeObservingView:(id)view didChangeSize:(CGSize)size;
-(void)_invalidateSegmentLayout;
-(void)_invalidateContentLayout;
-(void)viewDidDisappear:(BOOL)view;
-(void)viewWillDisappear:(BOOL)view;
-(void)viewDidAppear:(BOOL)view;
-(void)viewWillAppear:(BOOL)view;
-(BOOL)shouldAutomaticallyForwardAppearanceMethods;
-(id)_viewIfLoaded;
-(void)viewWillLayoutSubviews;
-(void)_layoutContentIfNecessary;
-(void)_setContentViewContentOffset:(CGPoint)offset animated:(BOOL)animated;
-(BOOL)_isChildViewControllerViewLoadedInContentView:(id)contentView;
-(void)_layoutSegmentsIfNecessary;
-(void)_layoutHeaderViewIfNecessary;
-(void)_backgroundContrastDidChange:(id)_backgroundContrast;
-(void)viewDidLoad;
-(void)loadView;
-(void)_loadContentView;
-(id)_newSwipeGestureRecognizerWithDirection:(unsigned)direction;
-(void)_loadHeaderView;
-(int)layoutMode;
-(float)_headerViewHeightForMode:(int)mode;
-(CGRect)_modeControlFrameWithHeaderBounds:(CGRect)headerBounds forMode:(int)mode;
-(void)dealloc;
@end

