/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBLockScreenActionContext.h"

@class BBBulletin, NSString;

__attribute__((visibility("hidden")))
@interface SBMutableLockScreenActionContext : SBLockScreenActionContext {
}
@property(assign, nonatomic) BBBulletin* bulletin;
@property(assign, nonatomic) BOOL requiresAuthentication;
@property(assign, nonatomic) BOOL canBypassPinLock;
@property(assign, nonatomic) BOOL deactivateAwayController;
@property(assign, nonatomic) BOOL requiresUIUnlock;
@property(copy, nonatomic) id action;
@property(retain, nonatomic) NSString* shortLockLabel;
@property(retain, nonatomic) NSString* lockLabel;
@property(retain, nonatomic) NSString* identifier;
@end

