/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "UIDynamicAnimatorDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "SpringBoard-Structs.h"

@class UIDynamicAnimator, SBBounceSettings, SBBounceBehavior, NSString, SBBouncingSystem, _SBNotificationCenterBouncingItem;

__attribute__((visibility("hidden")))
@interface SBNotificationCenterBounceAnimator : XXUnknownSuperclass <UIDynamicAnimatorDelegate> {
	UIDynamicAnimator* _animator;
	SBBouncingSystem* _system;
	SBBounceBehavior* _behavior;
	_SBNotificationCenterBouncingItem* _item;
	id _completion;
	SBBounceSettings* _settings;
	CGRect _targetFrame;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(copy, nonatomic, getter=_completion, setter=_setCompletion:) id completion;
@property(retain, nonatomic, getter=_behavior, setter=_setBehavior:) SBBounceBehavior* behavior;
@property(readonly, assign, nonatomic, getter=_animator) UIDynamicAnimator* animator;
-(void)dynamicAnimatorDidPause:(id)dynamicAnimator;
-(void)_updateSettings;
-(void)beginBounceWithInitialFrame:(CGRect)initialFrame targetFrame:(CGRect)frame velocity:(CGPoint)velocity removingGravityAtMidway:(BOOL)midway stepper:(id)stepper completion:(id)completion;
-(void)dealloc;
-(id)initWithReferenceBounds:(CGRect)referenceBounds settings:(id)settings;
@end

