/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBAlertView.h"

@class SBUIPasscodeViewWithLockScreenStyle, UIView;
@protocol SBPasscodeEntryAlertViewDelegate, SBUIPasscodeLockView;

__attribute__((visibility("hidden")))
@interface SBPasscodeEntryAlertView : SBAlertView {
	SBUIPasscodeViewWithLockScreenStyle* _passcodeView;
	BOOL _dismissing;
	id<SBPasscodeEntryAlertViewDelegate> _delegate;
}
@property(readonly, assign, nonatomic) UIView<SBUIPasscodeLockView>* passcodeLockView;
@property(assign, nonatomic) id<SBPasscodeEntryAlertViewDelegate> delegate;
-(void)_animatePasscodeViewsToVisible:(BOOL)visible completion:(id)completion;
-(void)_dismissAnimationCompleted;
-(id)_passcodeViewGenerator;
-(void)layoutForInterfaceOrientation:(int)interfaceOrientation;
-(BOOL)isReadyToBeRemovedFromView;
-(void)alertDisplayBecameVisible;
-(void)alertDisplayWillBecomeVisible;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
@end

