/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "SBTestRecipe.h"

@class SBAppSwitcherTwoSectionFakeDataSource, NSString;
@protocol SBAppSwitcherPeopleDataSource;

__attribute__((visibility("hidden")))
@interface SBPeopleShuffleTestRecipe : XXUnknownSuperclass <SBTestRecipe> {
	BOOL _isUsingFakeDatasource;
	id<SBAppSwitcherPeopleDataSource> _realDatasource;
	SBAppSwitcherTwoSectionFakeDataSource* _fakeDataSource;
	int _upCount;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
+(id)title;
-(void)_switchToRealDatasource;
-(void)_switchToFakeDatasource;
-(id)_peopleController;
-(void)handleVolumeDecrease;
-(void)handleVolumeIncrease;
-(void)dealloc;
-(id)init;
@end

