/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSLock, NSDictionary, NSString, NSSet, NSOrderedSet;

__attribute__((visibility("hidden")))
@interface SBPlatformController : XXUnknownSuperclass {
	long _defaultIconInfoOnce;
	NSDictionary* _defaultStarkIconState;
	NSDictionary* _defaultIconState;
	NSOrderedSet* _defaultIconStateDisplayIdentifiers;
	NSLock* _iconStateDisplayIdentifiersLock;
	NSSet* _iconStateDisplayIdentifiers;
	NSString* _localizedDeviceName;
	BOOL _hasGasGauge;
	BOOL _supportsOpenGLES2;
	BOOL _internalInstall;
	BOOL _carrierInstall;
	BOOL _singleCoreDevice;
}
+(id)uniqueDeviceIdentifier;
+(id)deviceClass;
+(id)productType;
+(id)hardwareModel;
+(id)systemBuildVersion;
+(id)sharedInstance;
-(void)_visibleIdentifiersChanged:(id)changed;
-(void)_loadDefaultIconInfoIfNecessary;
-(BOOL)isSingleCoreDevice;
-(BOOL)isDeveloperInstall;
-(BOOL)isCarrierInstall;
-(BOOL)isInternalInstall;
-(BOOL)supportsOpenGLES2;
-(BOOL)hasGasGauge;
-(id)localizedPlatformName;
-(id)iconStateDisplayIdentifiers;
-(void)registerForIconVisibilityChanges;
-(id)defaultIconStateDisplayIdentifiers;
-(id)defaultStarkIconState;
-(id)defaultIconState;
-(void)dealloc;
-(id)init;
@end

