/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableDictionary, NSObject;
@protocol OS_dispatch_queue;

__attribute__((visibility("hidden")))
@interface SBPushStore : XXUnknownSuperclass {
	NSObject<OS_dispatch_queue>* _notificationsQueue;
	NSObject<OS_dispatch_queue>* _settingsQueue;
	NSMutableDictionary* _observersByBundleID;
}
+(id)uniqueIdentifierForNotification:(id)notification;
+(void)migratePushStore;
+(id)sharedInstance;
+(void)initialize;
-(void)setDesiredSystemNotificationTypes:(unsigned)types forBundleID:(id)bundleID;
-(unsigned)desiredSystemNotificationTypesForBundleID:(id)bundleID;
-(BOOL)userDeniedNotificationsForBundleID:(id)bundleID;
-(void)setUserDeniedNotifications:(BOOL)notifications forBundeID:(id)bundeID;
-(void)setUserNotificationSettings:(id)settings forBundeID:(id)bundeID;
-(BOOL)_setUserNotificationSettings:(id)settings forBundeID:(id)bundeID;
-(id)effectiveUserNotificationSettingsForBundleID:(id)bundleID;
-(id)_effectiveUserNotificationSettingsForBundleID:(id)bundleID;
-(void)setEffectiveNotificationTypes:(unsigned)types forBundleID:(id)bundleID;
-(unsigned)effectiveNotificationTypesForBundleID:(id)bundleID;
-(unsigned)_effectiveNotificationTypesForBundleID:(id)bundleID;
-(void)setSupportedNotificationTypes:(unsigned)types forBundleID:(id)bundleID;
-(unsigned)supportedNotificationTypesForBundleID:(id)bundleID;
-(unsigned)_supportedNotificationTypesForBundleID:(id)bundleID;
-(void)notePushSettingsChangedForBundleID:(id)bundleID;
-(void)notePushDeclinedForBundleID:(id)bundleID;
-(void)notePushAcceptedForBundleID:(id)bundleID;
-(id)lastUpdateDateForBundleID:(id)bundleID;
-(id)bundleIDsWithUpdatesSince:(id)updatesSince;
-(id)savedNotificationsForBundleID:(id)bundleID;
-(id)savedNotificationDataForBundleID:(id)bundleID;
-(void)makeTestNotificationStores;
-(id)removeNotificationsPassingTest:(id)test forBundleID:(id)bundleID;
-(void)removeAllNotificationsForBundleID:(id)bundleID;
-(void)removeAllLocalNotificationsForBundleID:(id)bundleID;
-(void)removeLocalNotification:(id)notification forBundleID:(id)bundleID;
-(void)saveLocalNotification:(id)notification forBundleID:(id)bundleID;
-(void)saveRemoteNotificationWithMessage:(id)message soundName:(id)name actionText:(id)text badge:(id)badge userInfo:(id)info launchImage:(id)image category:(id)category forBundleID:(id)bundleID;
-(void)_saveNotificationWithMessage:(id)message soundName:(id)name actionText:(id)text badge:(id)badge userInfo:(id)info launchImage:(id)image fullDetails:(id)details soundIsRingtone:(BOOL)ringtone isRemoteNotification:(BOOL)notification category:(id)category forBundleID:(id)bundleID;
-(id)pathForSoundName:(id)soundName inApp:(id)app;
-(void)clearNotificationsForBundleID:(id)bundleID;
-(void)unregisterAppForNotificationsWithBundleID:(id)bundleID;
-(BOOL)_removeNotificationsForBundleID:(id)bundleID;
-(void)registerAppForNotificationsWithBundleID:(id)bundleID;
-(BOOL)_saveNotificationList:(id)list toPath:(id)path;
-(id)_allNotificationsFromPath:(id)path;
-(id)_allNotificationDataFromPath:(id)path;
-(BOOL)_notificationDataExistsAtPath:(id)path;
-(id)_notificationStoreFilenameForBundleID:(id)bundleID;
-(void)_notifyObserversNotificationsDidChangeForBundleID:(id)_notifyObserversNotifications;
-(void)_enumerateObserversForBundleID:(id)bundleID usingBlock:(id)block;
-(void)removeObserver:(id)observer forBundleID:(id)bundleID;
-(void)addObserver:(id)observer forBundleID:(id)bundleID;
-(id)_observersForBundleID:(id)bundleID;
-(void)dealloc;
-(id)init;
@end

