/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "UIAlertViewDelegate.h"

@class NSString, NSMutableIndexSet, SBUserInstalledApplicationIcon;

__attribute__((visibility("hidden")))
@interface SBRelatedDataDeletionAlertItem : XXUnknownSuperclass <UIAlertViewDelegate> {
	SBUserInstalledApplicationIcon* _icon;
	NSMutableIndexSet* _relatedDataStores;
	NSMutableIndexSet* _dataStoresToPurge;
	int _deleteButtonIndex;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
-(BOOL)dismissOnLock;
-(BOOL)shouldShowInLockScreen;
-(void)configure:(BOOL)configure requirePasscodeForActions:(BOOL)actions;
-(void)alertView:(id)view clickedButtonAtIndex:(int)index;
-(BOOL)_hasUnconsideredDataStores;
-(unsigned)_currentDataStoreCandidate;
-(void)setHasGameKitData:(BOOL)data;
-(void)setHasHealthKitData:(BOOL)data;
-(void)dealloc;
-(id)initWithIcon:(id)icon;
@end

