/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "NSCoding.h"

@class NSString, NSDate, NSData;

__attribute__((visibility("hidden")))
@interface SBRemoteNotificationClient : XXUnknownSuperclass <NSCoding> {
	NSString* _bundleIdentifier;
	NSString* _environment;
	NSData* _lastKnownDeviceToken;
	NSDate* _missingDate;
	BOOL _backgroundDeliveryDisabled;
	int _dayOfLastNewsstandPush;
	unsigned _dailyCountOfNewsstandPushes;
	BOOL _backgroundAppRefreshAllowed;
	BOOL _wantsPush;
	NSString* _pushDisabledReason;
}
@property(assign, nonatomic, getter=doesWantPush) BOOL wantsPush;
@property(assign, nonatomic, getter=isBackgroundAppRefreshAllowed) BOOL backgroundAppRefreshAllowed;
@property(retain, nonatomic) NSString* pushDisabledReason;
@property(readonly, assign, nonatomic, getter=isPushEnabled) BOOL pushEnabled;
@property(readonly, assign, nonatomic) BOOL supportsBackgroundAppRefresh;
@property(readonly, assign, nonatomic, getter=isNewsstandApplication) BOOL newsstandApplication;
@property(assign, nonatomic) unsigned dailyCountOfNewsstandPushes;
@property(assign, nonatomic) int dayOfLastNewsstandPush;
@property(assign, nonatomic) BOOL backgroundDeliveryDisabled;
@property(retain, nonatomic) NSDate* missingDate;
@property(retain, nonatomic) NSData* lastKnownDeviceToken;
@property(retain, nonatomic) NSString* environment;
@property(readonly, retain, nonatomic) NSString* bundleIdentifier;
-(BOOL)isNewsstandPushEnabled;
-(BOOL)allowsUserNotifications;
-(id)application;
-(void)encodeWithCoder:(id)coder;
-(id)initWithCoder:(id)coder;
-(BOOL)wantsPushWithCoder:(id)coder;
-(BOOL)backgroundAppRefreshAllowedForBundleIdentifier:(id)bundleIdentifier;
-(void)dealloc;
-(id)initWithBundleIdentifier:(id)bundleIdentifier;
@end

