/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBReachabilityTrigger.h"

@class NSTimer;

__attribute__((visibility("hidden")))
@interface SBReachabilityTapTrigger : SBReachabilityTrigger {
	NSTimer* _tapToTapExpirationTimer;
	NSTimer* _pendingDebounceTimer;
	BOOL _debouncedHome;
	NSTimer* _debounceTimer;
	BOOL _debounced;
	unsigned _numberOfTaps;
	unsigned _currentNumberOfTaps;
	BOOL _reachabilityWasTriggered;
}
@property(assign, nonatomic) unsigned numberOfTaps;
-(void)biometricEventMonitor:(id)monitor handleBiometricEvent:(unsigned)event;
-(void)_debounceTimerFired:(id)fired;
-(void)_setDebounceTimer;
-(void)_clearDebounceTimer;
-(void)_clearPendingTimerFired:(id)fired;
-(void)_setPendingDebounceTimer;
-(void)_clearPendingDebounceTimer;
-(void)_setExpirationTimer;
-(void)_clearExpirationTimer;
-(void)_expirationTimerFired:(id)fired;
-(void)clearPendingReachabilityTrigger;
-(void)dealloc;
-(id)initWithDelegate:(id)delegate;
@end

