/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBFolderView.h"
#import "SpringBoard-Structs.h"
#import "SBSearchGestureObserver.h"
#import "UIGestureRecognizerDelegate.h"
#import "_UISettingsKeyObserver.h"

@class SBRootFolder, SBSearchViewController, TPLegacyLCDTextView, SBDockIconListView, NSString, SBDockView, SBFParallaxSettings;

__attribute__((visibility("hidden")))
@interface SBRootFolderView : SBFolderView <_UISettingsKeyObserver, SBSearchGestureObserver, UIGestureRecognizerDelegate> {
	SBDockView* _dockView;
	SBDockIconListView* _dockListView;
	BOOL _dockViewBorrowed;
	TPLegacyLCDTextView* _idleTextView;
	SBFParallaxSettings* _parallaxSettings;
	float _searchGestureProgress;
	float _reachabilityYOffset;
	BOOL _layingOutForReachability;
	SBSearchViewController* _searchViewController;
	unsigned _dockEdge;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(assign, nonatomic, getter=isDockViewBorrowed) BOOL dockViewBorrowed;
@property(assign, nonatomic) unsigned dockEdge;
@property(readonly, retain, nonatomic) SBSearchViewController* searchViewController;
@property(retain, nonatomic) SBRootFolder* folder;
-(void)_handleReachabilityDectivatedAnimate:(BOOL)animate completion:(id)completion;
-(void)_handleReachabilityActivatedAnimate:(BOOL)animate completion:(id)completion;
-(float)reachabilityYOffset;
-(void)handleReachabilityActivated:(BOOL)activated animated:(BOOL)animated completion:(id)completion;
-(void)handleCancelReachabilityGesture:(id)gesture;
-(void)searchGesture:(id)gesture changedPercentComplete:(float)complete;
-(void)settings:(id)settings changedValueForKey:(id)key;
-(void)_configureParallax;
-(void)lcdTextViewCompletedScroll:(id)scroll;
-(void)setIdleText:(id)text;
-(BOOL)_updatesWallpaperRelativeCenter;
-(void)cleanUpAfterZoomAnimation;
-(void)prepareForZoomAnimation;
-(void)layoutIconLists:(double)lists domino:(BOOL)domino forceRelayout:(BOOL)relayout;
-(void)tearDownListViews;
-(void)_updateEditingStateAnimated:(BOOL)animated;
-(void)resetIconListViews;
-(id)iconListViewAtPoint:(CGPoint)point;
-(id)iconListViewAtIndex:(unsigned)index;
-(void)returnDockView;
-(void)borrowDockView;
-(void)_enableUserInteractionAfterSignificantAnimation;
-(void)_disableUserInteractionBeforeSignificantAnimation;
-(void)fadeContentForMinificationFraction:(float)minificationFraction;
-(void)fadeContentForMagnificationFraction:(float)magnificationFraction;
-(void)didAnimate;
-(void)willAnimate;
-(void)updateDockViewOrientation;
-(void)setDockVerticalStretch:(float)stretch;
-(void)setDockOffscreenFraction:(float)fraction;
-(id)dockView;
-(void)_layoutSubviews;
-(void)layoutDockView;
-(CGRect)effectivePageControlFrame;
-(void)layoutViewsForSearch;
-(CGRect)effectiveDockFrame;
-(float)effectiveStatusBarHeight;
-(void)setLegibilitySettings:(id)settings;
-(void)setOrientation:(int)orientation;
-(void)setNeedsLayout;
-(void)returnScalingView;
-(void)dealloc;
-(id)initWithFolder:(id)folder orientation:(int)orientation viewMap:(id)map forSnapshot:(BOOL)snapshot;
-(id)initWithFolder:(id)folder orientation:(int)orientation viewMap:(id)map;
@end

