/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class SBFadeAnimationSettings, SBAlertItemsSettings, SBIconColorSettings, SBAppParallaxSettings, NSString, SBHomeButtonSettings, SBFAnimationFactorySettings, SBAppSwitcherSettings, SBFolderSettings, SBRootAnimationSettings, SBCarDisplaySettings, SBFWallpaperSettings, SBLockScreenTestPluginSettings, SBReachabilitySettings, SBLegibilitySettings, SBLockScreenSettings, SBLockScreenSlideUpAppSettings, SBControlCenterSettings, SBNotificationCenterSettings;

__attribute__((visibility("hidden")))
@interface SBRootSettings : XXUnknownSuperclass {
	BOOL _preventLockover;
	SBAppParallaxSettings* _parallaxSettings;
	SBFolderSettings* _folderSettings;
	SBRootAnimationSettings* _rootAnimationSettings;
	SBControlCenterSettings* _controlCenterSettings;
	SBAppSwitcherSettings* _appSwitcherSettings;
	SBLockScreenSettings* _lockScreenSettings;
	SBCarDisplaySettings* _carDisplaySettings;
	SBLockScreenTestPluginSettings* _lockScreenTestPluginSettings;
	SBIconColorSettings* _iconColorSettings;
	SBFadeAnimationSettings* _fadeAnimationSettings;
	SBAlertItemsSettings* _alertItemsSettings;
	SBNotificationCenterSettings* _notificationCenterSettings;
	SBLegibilitySettings* _legibilitySettings;
	SBFWallpaperSettings* _wallpaperSettings;
	SBFAnimationFactorySettings* _animationSettings;
	SBHomeButtonSettings* _homeButtonSettings;
	SBLockScreenSlideUpAppSettings* _lockScreenSlideUpAppSettings;
	SBReachabilitySettings* _reachabilitySettings;
	NSString* _testRecipeClassName;
}
@property(assign) BOOL preventLockover;
@property(retain) NSString* testRecipeClassName;
@property(retain) SBReachabilitySettings* reachabilitySettings;
@property(retain) SBLockScreenSlideUpAppSettings* lockScreenSlideUpAppSettings;
@property(retain) SBHomeButtonSettings* homeButtonSettings;
@property(retain) SBFAnimationFactorySettings* animationSettings;
@property(retain) SBFWallpaperSettings* wallpaperSettings;
@property(retain) SBLegibilitySettings* legibilitySettings;
@property(retain) SBNotificationCenterSettings* notificationCenterSettings;
@property(retain) SBAlertItemsSettings* alertItemsSettings;
@property(retain) SBFadeAnimationSettings* fadeAnimationSettings;
@property(retain) SBIconColorSettings* iconColorSettings;
@property(retain) SBLockScreenTestPluginSettings* lockScreenTestPluginSettings;
@property(retain) SBCarDisplaySettings* carDisplaySettings;
@property(retain) SBLockScreenSettings* lockScreenSettings;
@property(retain) SBAppSwitcherSettings* appSwitcherSettings;
@property(retain) SBControlCenterSettings* controlCenterSettings;
@property(retain) SBRootAnimationSettings* rootAnimationSettings;
@property(retain) SBFolderSettings* folderSettings;
@property(retain) SBAppParallaxSettings* parallaxSettings;
+(id)settingsControllerModule;
-(BOOL)_hasPreviousSettings;
-(void)setDefaultValues;
@end

