/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBFolderController.h"

@class SBRootFolder, SBRootFolderView, UIWindow;

__attribute__((visibility("hidden")))
@interface SBRootFolderController : SBFolderController {
	BOOL _managesStatusBarWidth;
	UIWindow* _dockAnimationWindow;
}
@property(assign, nonatomic) BOOL managesStatusBarWidth;
@property(retain, nonatomic) UIWindow* dockAnimationWindow;
@property(assign, nonatomic) unsigned dockEdge;
@property(readonly, retain, nonatomic) SBRootFolderView* contentView;
@property(retain, nonatomic) SBRootFolder* folder;
+(Class)listViewClass;
-(void)didRotateFromInterfaceOrientation:(int)interfaceOrientation;
-(void)willAnimateRotationToInterfaceOrientation:(int)interfaceOrientation duration:(double)duration;
-(void)willRotateToInterfaceOrientation:(int)interfaceOrientation duration:(double)duration;
-(UIEdgeInsets)statusBarInsetsForOrientation:(int)orientation;
-(void)_configureAppStatusBarInsetsForOrientation:(int)orientation;
-(void)_configureAppStatusBarInsets;
-(void)_configureAppStatusBarInsetsAnimated:(BOOL)animated;
-(void)_configureDockViewForOrientationWithoutAnimation:(int)orientationWithoutAnimation;
-(void)_configureDockViewForOrientationDuringAnimation:(int)orientationDuringAnimation;
-(BOOL)_dockLayoutReversedForInterfaceOrientation:(int)interfaceOrientation;
-(unsigned)_dockEdgeForInterfaceOrientation:(int)interfaceOrientation;
-(BOOL)_shouldSlideDockOutDuringRotationFromOrientation:(int)orientation toOrientation:(int)orientation2;
-(BOOL)_isDockSwitchedForOrientation:(int)orientation;
-(void)prepareToClose;
-(void)prepareToOpen;
-(void)addAdditionalInnerFolderAnimations;
-(BOOL)popFolderAnimated:(BOOL)animated completion:(id)completion;
-(BOOL)pushFolder:(id)folder animated:(BOOL)animated completion:(id)completion;
-(BOOL)_listIndexIsVisible:(unsigned)visible;
-(CGRect)_autoscrollExclusionRegion;
-(void)setDockVerticalStretch:(float)stretch;
-(void)setDockOffscreenFraction:(float)fraction;
-(id)dockListView;
-(BOOL)isDisplayingIcon:(id)icon;
-(void)setIdleText:(id)text;
-(BOOL)setCurrentPageIndex:(int)index animated:(BOOL)animated;
-(id)folderControllers;
-(unsigned)_depth;
-(Class)_contentViewClass;
-(void)dealloc;
-(id)initWithFolder:(id)folder orientation:(int)orientation viewMap:(id)map;
@end

