/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBFolder.h"

@class SBIconListModel;

__attribute__((visibility("hidden")))
@interface SBRootFolder : SBFolder {
}
@property(retain, nonatomic) SBIconListModel* dock;
@property(readonly, assign, nonatomic) BOOL supportsDock;
+(BOOL)isRootFolderClass;
-(BOOL)isRootFolder;
-(id)nodeDescriptionWithPrefix:(id)prefix;
-(id)nodeIdentifier;
-(void)_setDock:(id)dock;
-(void)placeIconsOnFirstPage:(id)page;
-(id)_listsForCompaction;
-(BOOL)canEditDisplayName;
-(BOOL)canRemoveIcons;
@end

