/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableArray, UIView, UIWindow, UIScreen;

__attribute__((visibility("hidden")))
@interface SBScreenFlash : XXUnknownSuperclass {
	NSMutableArray* _flashCompletionBlocks;
	UIScreen* _screen;
	UIWindow* _flashWindow;
	UIView* _flashView;
	BOOL _windowVisible;
}
+(id)mainScreenFlasher;
-(void)_animationDidStop:(id)_animation finished:(id)finished context:(void*)context;
-(void)_orderWindowFront:(id)front withColor:(id)color;
-(void)_orderWindowOut:(id)anOut;
-(void)_tearDown;
-(void)_createUIWithColor:(id)color;
-(void)flashColor:(id)color withCompletion:(id)completion;
-(void)flashWhiteWithCompletion:(id)completion;
-(void)dealloc;
-(id)initWithScreen:(id)screen;
@end

