/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSDictionary;

__attribute__((visibility("hidden")))
@interface SBScrollViewLayoutInfos : XXUnknownSuperclass {
	NSDictionary* _indexPathsToFrames;
	NSDictionary* _sectionToNumberOfItems;
	NSDictionary* _sectionToPlaceholderFrames;
	float _contentWidth;
	float _presentationOffset;
	int _numberOfSections;
}
@property(assign, nonatomic) int numberOfSections;
@property(assign, nonatomic) float presentationOffset;
@property(assign, nonatomic) float contentWidth;
@property(retain, nonatomic) NSDictionary* sectionToPlaceholderFrames;
@property(retain, nonatomic) NSDictionary* sectionToNumberOfItems;
@property(retain, nonatomic) NSDictionary* indexPathsToFrames;
-(id)indexPathsOfVisibleItemsInBounds:(CGRect)bounds;
-(CGRect)frameForSectionPlaceholder:(int)sectionPlaceholder;
-(CGRect)frameForIndexPath:(id)indexPath;
-(unsigned)indexOfLastItemInSection:(unsigned)section;
-(unsigned)numberOfItemsInSection:(unsigned)section;
-(void)dealloc;
@end

