/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "NSCopying.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class SBAppSwitcherPeopleContactItem;

__attribute__((visibility("hidden")))
@interface SBScrollViewItemWrapper : XXUnknownSuperclass <NSCopying> {
	unsigned _section;
	SBAppSwitcherPeopleContactItem* _item;
	unsigned _itemIndex;
}
@property(readonly, assign, nonatomic) SBAppSwitcherPeopleContactItem* item;
@property(readonly, assign, nonatomic) unsigned itemIndex;
@property(readonly, assign, nonatomic) unsigned section;
-(id)copyWithZone:(NSZone*)zone;
-(BOOL)isEqual:(id)equal;
-(unsigned)hash;
-(void)dealloc;
-(id)initWithSection:(unsigned)section itemIndex:(unsigned)index item:(id)item;
@end

