/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "SpringBoard-Structs.h"
#import "SBSearchGestureObserver.h"

@class UIButton, UITextField, NSString;
@protocol SBSearchHeaderDelegate;

__attribute__((visibility("hidden")))
@interface SBSearchHeader : XXUnknownSuperclass <SBSearchGestureObserver> {
	UIButton* _cancelButton;
	UIEdgeInsets _cancelMargins;
	UIEdgeInsets _margins;
	UITextField* _searchField;
	id<SBSearchHeaderDelegate> _delegate;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(assign, nonatomic) id<SBSearchHeaderDelegate> delegate;
@property(readonly, retain, nonatomic) UITextField* searchField;
+(id)keyPathsForValuesAffectingRightCancelMargin;
+(id)keyPathsForValuesAffectingLeftCancelMargin;
+(id)keyPathsForValuesAffectingRightMargin;
+(id)keyPathsForValuesAffectingLeftMargin;
+(id)barTintColor;
-(void)searchGesture:(id)gesture changedPercentComplete:(float)complete;
-(void)_cancelButtonPressed;
-(id)hitTest:(CGPoint)test withEvent:(id)event;
-(void)layoutSubviews;
-(CGSize)sizeThatFits:(CGSize)fits;
-(float)rightCancelMargin;
-(float)leftCancelMargin;
-(float)rightMargin;
-(float)leftMargin;
-(void)updatePlaceholder;
-(void)updateMargins;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
@end

