/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSArray, SPSearchResult, SPSearchResultSection, SBSearchResultsActionManager;

__attribute__((visibility("hidden")))
@interface SBSearchResultsAction : XXUnknownSuperclass {
	SPSearchResult* _result;
	SPSearchResultSection* _section;
	NSArray* _urls;
	SBSearchResultsActionManager* _actionManager;
}
@property(assign, nonatomic) SBSearchResultsActionManager* actionManager;
@property(retain, nonatomic) NSArray* urls;
@property(readonly, assign) SPSearchResultSection* section;
@property(readonly, assign) SPSearchResult* result;
+(id)actionForResult:(id)result inSection:(id)section;
-(void)cancelAnimated:(BOOL)animated withCompletionBlock:(id)completionBlock;
-(id)performWithCompletionBlock:(id)completionBlock;
-(void)dealloc;
@end

