/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class UITextView, UIImageView, NSLayoutConstraint;

__attribute__((visibility("hidden")))
@interface SBSearchWikiMainContentCell : XXUnknownSuperclass {
	UITextView* _descriptionTextView;
	UIImageView* _cardImageView;
	NSLayoutConstraint* _cardImageViewHeightConstraint;
}
@property(assign) NSLayoutConstraint* cardImageViewHeightConstraint;
@property(assign) UIImageView* cardImageView;
@property(assign) UITextView* descriptionTextView;
-(CGSize)systemLayoutSizeFittingSize:(CGSize)size withHorizontalFittingPriority:(float)horizontalFittingPriority verticalFittingPriority:(float)priority;
-(void)awakeFromNib;
@end

