/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBSearchParsecSimpleCell.h"

@class UIImageView;

__attribute__((visibility("hidden")))
@interface SBSearchParsecSimpleChevronCell : SBSearchParsecSimpleCell {
	UIImageView* _chevronView;
}
@property(retain, nonatomic) UIImageView* chevronView;
+(BOOL)supportsSection:(id)section result:(id)result;
-(id)constantConstraints;
-(id)rightViewFrom:(id)from;
-(void)dealloc;
-(id)initWithStyle:(int)style reuseIdentifier:(id)identifier;
@end

