/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBSearchParsecSimpleChevronCell.h"


__attribute__((visibility("hidden")))
@interface SBSearchParsecSimpleMultiIconsCell : SBSearchParsecSimpleChevronCell {
	int _iconCount;
}
@property(assign) int iconCount;
+(id)keyPathsForValuesAffectingImageWidth;
+(BOOL)supportsSection:(id)section result:(id)result;
-(void)updateWithSection:(id)section result:(id)result traitCollection:(id)collection;
-(float)imageWidth;
-(float)iconInterspace;
-(float)iconWidth;
@end

