/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSDictionary, NSString, UIView, SBObservingLabel;

__attribute__((visibility("hidden")))
@interface SBSearchTableHeaderView : XXUnknownSuperclass {
	NSString* _reuseIdentifier;
	SBObservingLabel* _titleLabel;
	UIView* _separatorView;
	NSDictionary* _titleTextAttributes;
}
@property(retain, nonatomic) NSDictionary* titleTextAttributes;
@property(retain, nonatomic) UIView* separatorView;
@property(retain, nonatomic) SBObservingLabel* titleLabel;
@property(readonly, copy, nonatomic) NSString* reuseIdentifier;
@property(retain, nonatomic) NSString* title;
+(BOOL)requiresConstraintBasedLayout;
+(id)lineColor;
-(BOOL)isUserInteractionEnabled;
-(void)_contentSizeCategoryDidChange:(id)_contentSizeCategory;
-(void)updateFonts;
-(void)prepareForReuse;
-(void)dealloc;
-(id)initWithReuseIdentifier:(id)reuseIdentifier;
@end

