/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface SBSetupManager : XXUnknownSuperclass {
	BOOL _inSetupMode;
}
@property(readonly, assign, nonatomic, getter=isInSetupMode) BOOL inSetupMode;
+(id)sharedInstance;
-(BOOL)_setInSetupMode:(BOOL)setupMode;
-(BOOL)setupIsRunningForUpdateInstall;
-(BOOL)setupHasFinishedRestoringFromBackup;
-(BOOL)updateInSetupMode;
@end

