/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "SpringBoard-Structs.h"
#import "SBSearchResultDetailsViewController.h"

@class NSURLSessionDataTask, SPSearchResult, NSArray, SPSearchResultSection, UIColor, NSString;
@protocol SBSearchResultDetailsViewControllerDelegate;

__attribute__((visibility("hidden")))
@interface SBSearchMoviesViewController : XXUnknownSuperclass <SBSearchResultDetailsViewController> {
	NSURLSessionDataTask* _dataTask;
	id<SBSearchResultDetailsViewControllerDelegate> actionDelegate;
	SPSearchResult* _result;
	SPSearchResultSection* _section;
	NSArray* _movies;
}
@property(retain) UIColor* contentBackgroundColor;
@property(readonly, assign) BOOL wantsInset;
@property(assign) id<SBSearchResultDetailsViewControllerDelegate> actionDelegate;
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(retain) NSArray* movies;
@property(retain) SPSearchResultSection* section;
@property(retain) SPSearchResult* result;
+(id)viewControllerForResult:(id)result inSection:(id)section;
-(void)collectionView:(id)view didSelectItemAtIndexPath:(id)indexPath;
-(void)collectionView:(id)view didUnhighlightItemAtIndexPath:(id)indexPath;
-(void)collectionView:(id)view didHighlightItemAtIndexPath:(id)indexPath;
-(id)collectionView:(id)view cellForItemAtIndexPath:(id)indexPath;
-(CGSize)collectionView:(id)view layout:(id)layout sizeForItemAtIndexPath:(id)indexPath;
-(int)collectionView:(id)view numberOfItemsInSection:(int)section;
-(int)numberOfSectionsInCollectionView:(id)collectionView;
-(void)reloadData;
-(void)loadWithCompletionBlock:(id)completionBlock;
-(void)dealloc;
@end

