/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBSearchResultsAction.h"


__attribute__((visibility("hidden")))
@interface SBSearchResultsApplicationAction : SBSearchResultsAction {
}
-(void)_startDownloadingAppForStoreIdentifier:(unsigned long long)storeIdentifier bundleIdentifier:(id)identifier;
-(id)performWithCompletionBlock:(id)completionBlock;
@end

