/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class SBSearchResultsDetailsViewControllerAction;

__attribute__((visibility("hidden")))
@interface SBSearchDetailsViewControllerContainerViewController : XXUnknownSuperclass {
	SBSearchResultsDetailsViewControllerAction* _action;
}
@property(assign) SBSearchResultsDetailsViewControllerAction* action;
-(void)traitCollectionDidChange:(id)traitCollection;
@end

