/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBPasscodeEntryAlertView.h"
#import "SpringBoard-Structs.h"
#import "SBUIPasscodeLockViewDelegate.h"
#import "SBSIMLockEntryViewInterface.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface SBSIMLockEntryAlertView : SBPasscodeEntryAlertView <SBUIPasscodeLockViewDelegate, SBSIMLockEntryViewInterface> {
	NSString* _languageCode;
	NSString* _code;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
-(void)passcodeLockViewCancelButtonPressed:(id)pressed;
-(void)passcodeLockViewPasscodeEntered:(id)entered;
-(void)_doUnlock;
-(id)_failureLabel;
-(id)_failureTitle;
-(id)_pinAttemptsRemainingLabel;
-(void)_unlock;
-(id)_passcodeView;
-(void)alertDisplayWillBecomeVisible;
-(id)_passcodeViewGenerator;
-(void)setupUnlockAttemptState;
-(void)setupSuccess;
-(void)setupCurrentLockAttemptState;
-(void)setupFailureState;
-(id)label;
-(id)titleText;
-(id)localizedStringWithKey:(id)key;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame languageCode:(id)code;
@end

