/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString;

__attribute__((visibility("hidden")))
@interface SBSnapshotDataProviderContext : XXUnknownSuperclass {
	NSString* _sceneID;
	float _scale;
	BOOL _opaque;
}
@property(assign, nonatomic, getter=isOpaque) BOOL opaque;
@property(assign, nonatomic) float scale;
@property(copy, nonatomic) NSString* sceneID;
-(void)dealloc;
@end

