/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBUIAnimationControllerObserver.h"
#import "SBStarkToAppWorkspaceTransaction.h"

@class NSString, SBUIAnimationController, SBApplication;

__attribute__((visibility("hidden")))
@interface SBStarkAppToAppWorkspaceTransaction : SBStarkToAppWorkspaceTransaction <SBUIAnimationControllerObserver> {
	SBApplication* _fromApp;
	SBUIAnimationController* _animationController;
	BOOL _animatedActivation;
	BOOL _animatedDeactivation;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(readonly, assign, nonatomic) SBApplication* fromApp;
-(void)animationControllerDidFinishAnimation:(id)animationController;
-(void)animationController:(id)controller willBeginAnimation:(BOOL)animation;
-(id)_newAnimationFromLauncherToNowPlaying;
-(id)_newAnimationFromNowPlayingToLauncher;
-(id)_newAnimationFromNowPlayingToNowPlaying;
-(id)_newAnimationFromNowPlayingToApp;
-(id)_newAnimationFromLauncherToApp;
-(id)_newAnimationFromAppToLauncher;
-(id)_newAnimationFromAppToNowPlaying;
-(id)_newAnimationFromAppToApp;
-(void)_doCommit;
-(id)_animation;
-(void)_handleAppDidNotChange;
-(id)_defaultAnimationFactory;
-(id)_setupAnimationFrom:(id)from to:(id)to;
-(id)swizzledToDisplayIfNecessary;
-(void)_didComplete;
-(void)_didInterruptWithReason:(id)reason;
-(BOOL)_canBeInterrupted;
-(void)_endAnimation;
-(void)mainScreenApplicationSceneWillCommit:(id)mainScreenApplicationScene;
-(void)mainScreenApplicationUpdateScenesTransactionCompleted:(id)completed;
-(void)_fixupSettingsAndCommit;
-(void)_begin;
-(void)_beginAnimation;
-(void)_setupMilestonesFrom:(id)from to:(id)to;
-(void)_noteWillActivateApplicationOnMainScreen:(id)_note underLock:(BOOL)lock;
-(void)dealloc;
-(id)initWithMainScreenAlertManager:(id)mainScreenAlertManager starkScreenController:(id)controller from:(id)from to:(id)to;
@end

