/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBFolderView.h"
#import "SpringBoard-Structs.h"

@class UIButton, SBStarkIconLayoutOverrideStrategy;

__attribute__((visibility("hidden")))
@interface SBStarkFolderView : SBFolderView {
	BOOL _buttonUXEnabled;
	UIButton* _scrollLeftButton;
	UIButton* _scrollRightButton;
	CGSize _scrollButtonSize;
	SBStarkIconLayoutOverrideStrategy* _iconLayoutOverrideStrategy;
	UIEdgeInsets _listViewInsets;
}
@property(retain, nonatomic) SBStarkIconLayoutOverrideStrategy* iconLayoutOverrideStrategy;
-(void)_scrollButtonPressed:(id)pressed;
-(void)_updateScrollButtonStatesForIndex:(int)index;
-(void)_evaluateScrollingForListViewsIfNecessary;
-(void)_updatePageControlToIndex:(int)index;
-(void)_updateIconListFrames;
-(void)updateIconListViews;
-(void)resetIconListViews;
-(void)_layoutSubviews;
-(float)_offsetToCenterPageControlInSpaceForPageControl;
-(id)_newPageControl;
-(void)setInteractionAffordances:(unsigned)affordances;
-(void)dealloc;
-(id)initWithFolder:(id)folder orientation:(int)orientation viewMap:(id)map;
@end

