/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBStarkAppToAppWorkspaceTransaction.h"

@class SBAlert, SBAlertChangeTransaction;

__attribute__((visibility("hidden")))
@interface SBStarkImpersonatedAppToAppWorkspaceTransaction : SBStarkAppToAppWorkspaceTransaction {
	SBAlertChangeTransaction* _deactivateAlertTransaction;
	SBAlert* _deactivatingAlert;
	BOOL _animatedAppActivation;
}
-(void)animationControllerDidFinishAnimation:(id)animationController;
-(void)animationController:(id)controller willBeginAnimation:(BOOL)animation;
-(void)_deactivateAlertIfPossible;
-(void)_handleFailureToLaunch;
-(void)mainScreenApplicationUpdateScenesTransactionCompleted:(id)completed;
-(id)_newAnimationFromAppToLauncher;
-(id)_newAnimationFromAppToNowPlaying;
-(id)_newAnimationFromAppToApp;
-(void)_didComplete;
-(void)_setupMilestonesFrom:(id)from to:(id)to;
-(void)_doCommit;
-(void)dealloc;
-(id)initWithMainScreenAlertManager:(id)mainScreenAlertManager starkScreenController:(id)controller from:(id)from to:(id)to;
@end

