/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBAlertAdapter.h"


__attribute__((visibility("hidden")))
@interface SBStarkRelockUIAlert : SBAlertAdapter {
	BOOL _animatingDismiss;
}
-(void)_dismissAndLock;
-(void)_animateDismiss;
-(id)_animationFactory;
-(void)deactivate;
-(void)activate;
-(BOOL)hasTranslucentBackground;
-(void)handleAutoLock;
-(BOOL)handleLockButtonPressed;
-(BOOL)shouldPendAlertItemsWhileActive;
-(BOOL)handleMenuButtonHeld;
-(BOOL)handleMenuButtonDoubleTap;
-(BOOL)handleMenuButtonTap;
-(void)dealloc;
-(id)initWithViewController:(id)viewController;
-(id)init;
@end

