/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBStarkWorkspaceTransaction.h"

@class SBAlert;

__attribute__((visibility("hidden")))
@interface SBStarkAlertToAlertWorkspaceTransaction : SBStarkWorkspaceTransaction {
	SBAlert* _activatingAlert;
	SBAlert* _deactivatingAlert;
	BOOL _activation;
}
-(void)_begin;
-(id)debugDescription;
-(void)dealloc;
-(id)_initWithMainScreenAlertManager:(id)mainScreenAlertManager starkScreenController:(id)controller activatingAlert:(id)alert deactivatingAlert:(id)alert4 activation:(BOOL)activation;
-(id)initDeactivationWithMainScreenAlertManager:(id)mainScreenAlertManager starkScreenController:(id)controller from:(id)from to:(id)to;
-(id)initActivationWithMainScreenAlertManager:(id)mainScreenAlertManager starkScreenController:(id)controller from:(id)from to:(id)to;
@end

