/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "SBUIBannerSource.h"
#import "SBUIBannerTargetManagerObserver.h"

@class NSString, NSMutableArray;
@protocol SBUIBannerTarget;

__attribute__((visibility("hidden")))
@interface SBStarkBannerSource : XXUnknownSuperclass <SBUIBannerSource, SBUIBannerTargetManagerObserver> {
	id _allowedTargetIdentifier;
	id<SBUIBannerTarget> _target;
	NSMutableArray* _enqueuedItems;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
-(void)bannerTargetManager:(id)manager didRemoveTarget:(id)target;
-(void)bannerTargetManager:(id)manager didAddTarget:(id)target;
-(id)newBannerViewForContext:(id)context;
-(id)dequeueNextBannerItemForTarget:(id)target;
-(id)peekNextBannerItemForTarget:(id)target;
-(unsigned)enumerateAllItemsMatchingContext:(id)context withBlock:(id)block;
-(void)removeEnqueuedItemsAtIndexes:(id)indexes;
-(void)dismissCurrentItemFromTarget;
-(void)enqueueItem:(id)item;
-(id)indexesOfEnqueuedItemsMatchingContext:(id)enqueuedItemsMatchingContext;
-(id)currentItemFromTarget;
-(void)dealloc;
-(id)init;
-(id)initWithAllowedTargetIdentifier:(void*)allowedTargetIdentifier;
@end

