/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class UILabel, UIImageView;

__attribute__((visibility("hidden")))
@interface SBStarkRelockUIViewController : XXUnknownSuperclass {
	UIImageView* _imageView;
	CGSize _imageSize;
	UILabel* _label;
	float _labelOffset;
	CGSize _labelSize;
}
-(void)viewDidLayoutSubviews;
-(void)viewDidLoad;
-(void)dealloc;
@end

