/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class UILabel, UIImageView, UIColor, UIImage, UIView;

__attribute__((visibility("hidden")))
@interface SBStarkBannerViewButton : XXUnknownSuperclass {
	UILabel* _textLabel;
	UIColor* _unselectedTextColor;
	UIColor* _selectedTextColor;
	UIImage* _unselectedImage;
	UIImage* _selectedImage;
	UIView* _highlightView;
	UIImageView* _imageView;
	UIColor* _highlightColor;
}
@property(retain, nonatomic) UIColor* highlightColor;
@property(retain, nonatomic) UIImage* selectedImage;
@property(retain, nonatomic) UIImage* unselectedImage;
@property(retain, nonatomic) UIColor* selectedTextColor;
@property(retain, nonatomic) UIColor* unselectedTextColor;
@property(retain, nonatomic) UILabel* textLabel;
-(void)layoutSubviews;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
@end

