/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBStarkAlertToAppWorkspaceTransaction.h"

@class SBAlert, SBApplication;

__attribute__((visibility("hidden")))
@interface SBStarkAlertToImpersonatedAppWorkspaceTransaction : SBStarkAlertToAppWorkspaceTransaction {
	SBAlert* _fromAlert;
	SBAlert* _toAlert;
	SBApplication* _toApplication;
}
-(void)_activateAlert;
-(BOOL)_shouldDisallowSuspension;
-(void)_setupMilestonesFrom:(id)from to:(id)to;
-(void)_alertDidDeactivate;
-(void)_beginAnimation;
-(id)debugDescription;
-(void)dealloc;
-(id)initWithMainScreenAlertManager:(id)mainScreenAlertManager starkScreenController:(id)controller alert:(id)alert toApplication:(id)application;
@end

