/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBAlertItemsControllerObserver.h"
#import "SBStarkBannerSource.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface SBStarkAlertItemBannerSource : SBStarkBannerSource <SBAlertItemsControllerObserver> {
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
-(void)alertItemsController:(id)controller didDeactivateAlertItem:(id)item forReason:(int)reason;
-(void)alertItemsController:(id)controller didActivateAlertItem:(id)item;
-(void)alertItemsController:(id)controller willActivateAlertItem:(id)item;
-(void)dealloc;
-(id)initWithAllowedTargetIdentifier:(void*)allowedTargetIdentifier;
@end

