/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBStarkNotificationViewControllerDelegate.h"
#import "SBWindow.h"

@class NSString, SBStarkNotificationViewController, SBStarkScreenFocusController;

__attribute__((visibility("hidden")))
@interface SBStarkNotificationWindow : SBWindow <SBStarkNotificationViewControllerDelegate> {
	SBStarkScreenFocusController* _focusController;
	BOOL _assertingFocus;
	id _borrowScreenToken;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(retain, nonatomic) SBStarkNotificationViewController* rootViewController;
@property(retain, nonatomic) SBStarkScreenFocusController* focusController;
-(id)hitTest:(CGPoint)test withEvent:(id)event;
-(void)notificationViewController:(id)controller stateDidChangeFrom:(int)state;
-(void)notificationViewController:(id)controller willDisplayBannerView:(id)view;
-(void)dealloc;
-(id)initWithScreen:(id)screen layoutStrategy:(id)strategy debugName:(id)name scene:(id)scene;
@end

