/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBIconListView.h"


__attribute__((visibility("hidden")))
@interface SBStarkRootIconListView : SBIconListView {
	UIEdgeInsets _insets;
}
@property(assign, nonatomic) UIEdgeInsets insets;
+(unsigned)iconColumnsForInterfaceOrientation:(int)interfaceOrientation;
+(unsigned)maxVisibleIconRowsInterfaceOrientation:(int)orientation;
-(int)iconLocation;
-(float)sideIconInset;
-(float)bottomIconInset;
-(float)topIconInset;
-(Class)baseIconViewClass;
@end

