/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "FBApplicationLibraryObserver.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, SBPasscodeLockDisableAssertion, NSTimer;

__attribute__((visibility("hidden")))
@interface SBSyncController : XXUnknownSuperclass <FBApplicationLibraryObserver> {
	int _restoreState;
	int _resetState;
	int _restoreTimerState;
	NSTimer* _restoreTimer;
	NSTimer* _progressTimer;
	BOOL _showingResetUI;
	BOOL _appsChangedDuringSync;
	int _restoreStartedNotifyToken;
	int _restoreEndedNotifyToken;
	SBPasscodeLockDisableAssertion* _disableDeviceLockAssertion;
	BOOL _isAppSyncing;
	BOOL _inExtendedAppSyncCoalescePeriod;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
+(id)sharedInstance;
-(void)applicationLibrary:(id)library didRemoveApplications:(id)applications;
-(void)applicationLibrary:(id)library didReplaceApplications:(id)applications withApplications:(id)applications3;
-(void)applicationLibrary:(id)library didAddApplications:(id)applications;
-(void)_appInstallationNotification;
-(void)_setupRestoreTimer;
-(void)_restoreTimerFired:(id)fired;
-(BOOL)_isBackupAgentRunning;
-(void)_invalidateRestoreTimer;
-(void)_didEndResetting;
-(void)_delayedBeginReset;
-(void)_updateProgress;
-(void)_delayedQuitApplications;
-(void)_didEndRestoring:(int)restoring;
-(void)_finishEndRestoring;
-(void)_rebootNow;
-(void)_killApplications;
-(void)_notifyRestoreCanProceed;
-(void)_syncSessionDidEnd;
-(void)_syncSessionDidBegin;
-(void)_setRestoreState:(int)state;
-(void)_resetEnded:(id)ended;
-(void)_resetStarted:(id)started;
-(void)_wirelessSyncEnded:(id)ended;
-(void)_wirelessSyncBegan:(id)began;
-(BOOL)isInUse;
-(void)beginResetting:(BOOL)resetting;
-(int)resetState;
-(BOOL)isResetting;
-(void)cancelRestoring;
-(void)beginRestoring;
-(int)restoreState;
-(BOOL)isRestoring;
-(void)finishedTerminatingApplications;
-(void)stopObserving;
-(void)startObserving;
-(void)dealloc;
@end

