/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "SBModalLayoutCaching.h"

@class NSString, UILabel, UIImageView;

__attribute__((visibility("hidden")))
@interface SBTodayBulletinCell : XXUnknownSuperclass <SBModalLayoutCaching> {
	UILabel* _label;
	UIImageView* _iconImageView;
	int _layoutMode;
}
@property(assign, nonatomic) int layoutMode;
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(copy, nonatomic) NSString* labelText;
@property(assign, nonatomic) CGRect textRect;
+(id)defaultTextAttributes;
+(float)interCellSpacingInLayoutMode:(int)layoutMode;
+(id)defaultFontColor;
+(id)defaultFont;
-(void)layoutSubviews;
-(void)setIcon:(id)icon;
-(void)dealloc;
-(id)initWithStyle:(int)style reuseIdentifier:(id)identifier;
@end

