/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBUIStarkStartupAnimation.h"

@class NSMutableArray, SBStarkLockOutView;

__attribute__((visibility("hidden")))
@interface SBUIStarkStartupToLockoutAnimation : SBUIStarkStartupAnimation {
	NSMutableArray* _viewsToSlideUp;
	SBStarkLockOutView* _toLockoutView;
	unsigned _significantAnimationsRemaining;
}
-(void)_noteSignificantAnimationFinished;
-(void)_slideUpViewsWithSlideFactory:(id)slideFactory fadeFactory:(id)factory delayIncrement:(double)increment;
-(void)_finishViewForSlideUp:(id)slideUp;
-(void)_cleanupAnimation;
-(void)_startAnimation;
-(void)_prepareAnimation;
-(void)dealloc;
-(id)initFromLockoutView:(id)lockoutView toLockoutView:(id)lockoutView2 starkScreenController:(id)controller;
@end

