/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBIconAnimatorDelegate.h"
#import "SBUIAnimationZoomUpApp.h"

@class NSString, SBIconAnimator;

__attribute__((visibility("hidden")))
@interface SBUIAnimationZoomUpAppFromHome : SBUIAnimationZoomUpApp <SBIconAnimatorDelegate> {
	SBIconAnimator* _iconAnimator;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
-(void)iconAnimatorWasInvalidated:(id)invalidated;
-(void)cleanupZoom;
-(void)animateZoomWithCompletion:(id)completion;
-(void)prepareZoom;
-(void)dealloc;
@end

