/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBUIStarkScreenAnimationController.h"

@class SBDosidoAnimator, SBAlert, UIView, SBApplication;

__attribute__((visibility("hidden")))
@interface SBUIStarkDosidoAnimation : SBUIStarkScreenAnimationController {
	UIView* _fromView;
	UIView* _toView;
	UIView* _viewToHide;
	SBAlert* _alertImpersonator;
	SBApplication* _impersonatedApplication;
	SBDosidoAnimator* _dosidoAnimator;
	BOOL _animationFinished;
	BOOL _fromAssistant;
}
-(void)noteDependencyDidInvalidate;
-(void)_maybeReportAnimationFinished;
-(void)_applicationDependencyStateChanged;
-(void)_cleanupHosting;
-(double)_animationDelay;
-(void)_cleanupAnimation;
-(void)_startAnimation;
-(void)_prepareAnimation;
-(id)_animationProgressDependency;
-(BOOL)_waitsForApplicationActivationIfNecessary;
-(void)dealloc;
-(id)initFromAlertImpersonator:(id)alertImpersonator toApp:(id)app starkScreenController:(id)controller;
-(id)initFromApp:(id)app toAlertImpersonator:(id)alertImpersonator starkScreenController:(id)controller;
-(id)initFromApp:(id)app toApp:(id)app2 starkScreenController:(id)controller;
-(void)_commonInitFromView:(id)view toView:(id)view2 alert:(id)alert toDisplay:(id)display;
@end

