/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBUIStarkStartupAnimation.h"

@class UIStatusBar, FBWindowContextHostManager, UIView;

__attribute__((visibility("hidden")))
@interface SBUIStarkStartupToAppAnimation : SBUIStarkStartupAnimation {
	FBWindowContextHostManager* _contextHostManager;
	UIView* _viewToAnimate;
	UIStatusBar* _fakeStatusBar;
	BOOL _finished;
}
-(void)_finishedAnimation:(BOOL)animation;
-(void)_cleanupAnimation;
-(void)_cancelAnimation;
-(void)_startAnimation;
-(void)_reallyPrepareAnimation;
-(void)_prepareAnimation;
-(void)_applicationDependencyStateChanged;
-(id)_animationProgressDependency;
-(void)_setupStartDependencies;
-(id)_createViewToAnimate;
-(void)dealloc;
@end

