/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol SBUIBannerTargetBase <NSObject>
@property(readonly, assign, nonatomic) int bannerTargetIdiom;
@property(readonly, assign, nonatomic) void* bannerTargetIdentifier;
-(void)removeCachedBannerForContext:(id)context;
-(void)cacheBannerForContext:(id)context withCompletion:(id)completion;
-(void)dismissCurrentBannerContextForSource:(id)source;
-(id)currentBannerContextForSource:(id)source;
-(void)signalSource:(id)source;
-(BOOL)isShowingModalBanner;
-(void)modallyPresentBannerWithContext:(id)context;
-(void)unregisterSource:(id)source;
-(void)registerSource:(id)source;
@end

