/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol SBUserNotificationCapable <NSObject>
-(void)noteBadgeSetLocally;
-(void)scheduleLocalNotifications:(id)notifications replaceExistingNotifications:(BOOL)notifications2;
-(void)setBadge:(id)badge;
@end

