/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "SBUserNotificationCapable.h"

@class NSObject, NSString, SBApplication;
@protocol OS_dispatch_queue;

__attribute__((visibility("hidden")))
@interface SBUserNotificationPermissionController : XXUnknownSuperclass <SBUserNotificationCapable> {
	BOOL _queueSuspended;
	BOOL _showingAlert;
	BOOL _canPerformQueuedActions;
	NSString* _bundleIdentifier;
	NSObject<OS_dispatch_queue>* _performQueue;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(assign, nonatomic) BOOL canPerformQueuedActions;
@property(assign, nonatomic, getter=isShowingAlert) BOOL showingAlert;
@property(assign, nonatomic, getter=isQueueSuspended) BOOL queueSuspended;
@property(retain, nonatomic) NSObject<OS_dispatch_queue>* performQueue;
@property(copy, nonatomic) NSString* bundleIdentifier;
@property(readonly, retain, nonatomic) SBApplication* application;
+(void)evictControllerFromCache:(id)cache;
+(id)controllerForBundleIdentifier:(id)bundleIdentifier;
+(id)controllerForApplication:(id)application;
+(void)createCacheIfNecessary;
+(void)migratePushSettings:(unsigned)settings forBundleIdentifier:(id)bundleIdentifier;
-(void)noteBadgeSetLocally;
-(void)scheduleLocalNotifications:(id)notifications replaceExistingNotifications:(BOOL)notifications2;
-(void)setBadge:(id)badge;
-(void)setBadge:(id)badge onBehalfOfSystem:(BOOL)system;
-(void)saveRegisteredUserNotificationSettings:(id)settings userDeniedNotifications:(BOOL)notifications;
-(void)registerPrivilegedForAdditionalTypes:(unsigned)additionalTypes;
-(void)enqueueAction:(id)action;
-(id)effectiveUserNotificationSettings;
-(void)didDeactivateAlert:(id)alert reason:(int)reason;
-(void)notePermissionAlertAccepted:(BOOL)accepted withSettings:(id)settings makeAppDelegateCallback:(BOOL)callback;
-(void)saveRegisteredUserNotificationSettings:(id)settings;
-(void)unregisterUserNotificationSettings;
-(void)registerUserNotificationSettings:(id)settings makeAppDelegateCallback:(BOOL)callback;
-(void)registerSupportedNotificationTypes:(unsigned)types withEnabledNotificationSettings:(id)enabledNotificationSettings makeAppDelegateCallback:(BOOL)callback bypassAlert:(BOOL)alert;
-(id)settingsForRequestedSettings:(id)requestedSettings systemDesiredTypes:(unsigned)types;
-(void)setHaveRegisteredBefore:(BOOL)before;
-(BOOL)haveRegisteredBefore;
-(void)installedApplicationsChanged:(id)changed;
-(void)tearDownQueue;
-(void)dealloc;
-(id)initWithBundleIdentifier:(id)bundleIdentifier;
@end

