/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol SBVibrantBannerView <NSObject>
+(id)defaultColorForElement:(int)element;
-(void)setColor:(id)color forElement:(int)element;
-(id)colorForElement:(int)element;
@end

