/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SpringBoard-Structs.h"
#import "SBAlert.h"


__attribute__((visibility("hidden")))
@interface SBVoiceControlAlert : SBAlert {
	struct {
		unsigned isRePushingUpdates : 1;
		unsigned scrollsToTop : 1;
		unsigned isLayoutValid : 1;
	} _voiceControlFlags;
	BOOL _expectsFaceContact;
	BOOL _expectsFaceContactInLandscape;
}
+(void)_setNextRecognitionAudioInputPathForSession:(id)session resetting:(BOOL)resetting;
+(void)setNextRecognitionAudioInputPaths:(id)paths;
+(void)_configureSession:(id)session forAlert:(id)alert;
+(BOOL)_bluetoothDevicesPickable;
+(void)bluetoothDeviceTerminatedVoiceControl:(id)control;
+(void)bluetoothDeviceRequestedVoiceControl:(id)control;
+(BOOL)resetVoiceControlIfNecessary:(BOOL)necessary;
+(BOOL)shouldEnterVoiceControl;
+(void)unregisterForAlerts;
+(void)registerForAlerts;
+(id)pendingOrActiveAlert;
-(id)alertDisplayViewWithSize:(CGSize)size;
-(double)autoDimTime;
-(BOOL)handleMenuButtonTap;
-(void)handleHeadsetButtonUpFromActivation:(BOOL)activation;
-(void)_proximityChanged:(id)changed;
-(void)dealloc;
-(void)cancel;
-(void)cancelIfNotActivated;
-(void)activateWhenReady;
-(id)initFromMenuButton;
-(BOOL)expectsFaceContactInLandscape;
-(BOOL)expectsFaceContact;
-(void)setExpectsFaceContact:(BOOL)contact inLandscape:(BOOL)landscape;
-(void)setExpectsFaceContact:(BOOL)contact;
-(void)activate;
-(void)deactivate;
-(BOOL)allowsEventOnlySuspension;
-(id)initFromBluetoothDevice:(id)bluetoothDevice;
-(id)initFromWiredHeadsetButton;
-(id)init;
-(void)_setRoutingAttributesForWiredHeadset:(BOOL)wiredHeadset;
-(BOOL)recognitionSessionWillBeginAction:(id)recognitionSession;
-(void)_workspaceActivate;
-(id)_session;
-(void)_makeActive;
-(void)_resign;
@end

