/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBVoiceControlAlertDisplay.h"
#import "SpringBoard-Structs.h"


__attribute__((visibility("hidden")))
@interface SBVoiceControlMenuedAlertDisplay : SBVoiceControlAlertDisplay {
}
-(BOOL)_wasTriggeredByMenu;
@end

