/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "SBWallpaperObserver.h"

@class NSString, NSMutableSet;

__attribute__((visibility("hidden")))
@interface SBWallpaperEffectSnapshotCache : XXUnknownSuperclass <SBWallpaperObserver> {
	NSMutableSet* _mappedImageKeys;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
+(id)sharedInstance;
-(void)wallpaperWillChangeForVariant:(int)wallpaper;
-(id)snapshotForKey:(id)key withGenerationBlockIfNecessary:(id)generationBlockIfNecessary;
-(void)dealloc;
-(id)init;
@end

