/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class SBStarkScreenController;

__attribute__((visibility("hidden")))
@interface SBWaitForCarNowPlayingActiveTransaction : XXUnknownSuperclass {
	SBStarkScreenController* _screenController;
	double _timeout;
}
-(void)_begin;
-(void)dealloc;
-(id)initWithScreenController:(id)screenController timeout:(double)timeout;
@end

