/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBTestRecipe.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "FBApplicationProcessObserver.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface SBWindowManagerTestRecipe : XXUnknownSuperclass <FBApplicationProcessObserver, SBTestRecipe> {
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
+(id)title;
-(void)applicationProcessDidExit:(id)applicationProcess withContext:(id)context;
-(void)handleVolumeDecrease;
-(void)handleVolumeIncrease;
@end

