/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class UIImageView, UIButton;

__attribute__((visibility("hidden")))
@interface SBWidgetsSettingsTableViewCell : XXUnknownSuperclass {
	UIImageView* _dotImageView;
	BOOL _widgetEnabled;
	BOOL _showsDot;
	UIButton* _insertWidgetAccessoryButton;
}
@property(readonly, assign, nonatomic) UIButton* insertWidgetAccessoryButton;
@property(assign, nonatomic) BOOL showsDot;
@property(assign, nonatomic, getter=isWidgetEnabled) BOOL widgetEnabled;
-(void)layoutSubviews;
-(void)dealloc;
-(id)initWithStyle:(int)style reuseIdentifier:(id)identifier;
@end

