/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"

@class NSSet;

@protocol SBWidgetHandling <NSObject>
@property(readonly, assign, nonatomic) NSSet* visibleWidgetIDs;
-(BOOL)shouldRequestWidgetRemoteViewControllers;
-(void)enableAllWidgets:(id)widgets;
-(void)makeVisibleWidgetWithIdentifier:(id)identifier animated:(BOOL)animated completion:(id)completion;
-(void)updateWidgetsWithIdentifiers:(id)identifiers launchStats:(id)stats completion:(id)completion;
-(id)widgetWithIdentifier:(id)identifier;
@end

