/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class SBDisplayLayout, NSArray;

__attribute__((visibility("hidden")))
@interface SBWorkspaceAppsActivationRequest : XXUnknownSuperclass {
	NSArray* _applications;
	SBDisplayLayout* _displayLayout;
}
@property(readonly, assign, nonatomic) SBDisplayLayout* displayLayout;
@property(readonly, assign, nonatomic) NSArray* applications;
+(id)fullScreenActivationRequestForApp:(id)app;
+(id)homeScreenActivationRequest;
-(void)dealloc;
-(id)initWithApplications:(id)applications displayLayout:(id)layout;
@end

